import type { Content } from './types';

const content: Content = {
	days: [
		{
			k: 'Mon',
			label: 'Mon',
			prime: 'Recruitment pulls → Limit bouldering',
			sec: 'Contact strength / RFD, then hardest problems',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['recruit', 'limitboulder'],
		},
		{
			k: 'Tue',
			label: 'Tue',
			prime: 'Pinch block + Wrist / Sloper',
			sec: 'Abrahangs AM · antagonists',
			load: 'MOD',
			color: 'var(--gold)',
			ex: ['pinch', 'wrist', 'abra', 'antag'],
		},
		{
			k: 'Wed',
			label: 'Wed',
			prime: '7/3 Repeaters → Sport climbing',
			sec: 'Strength-endurance, critical force, pump',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['repeaters', 'sport'],
		},
		{
			k: 'Thu',
			label: 'Thu',
			prime: 'Heavy pull day + Sloper density',
			sec: 'Weighted pull-ups, OAP · Abrahangs AM',
			load: 'MOD',
			color: 'var(--violet)',
			ex: ['pull', 'slopdens', 'abra', 'antag'],
		},
		{
			k: 'Fri',
			label: 'Fri',
			prime: 'Max hangs (maintenance) + Density',
			sec: 'Tissue investment, MTJ density',
			load: 'MOD',
			color: 'var(--teal)',
			ex: ['maxhang', 'density'],
		},
		{
			k: 'Sat',
			label: 'Sat',
			prime: 'Outdoor / Performance',
			sec: 'Hangboard = warm-up only',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['perform'],
		},
		{
			k: 'Sun',
			label: 'Sun',
			prime: 'Full rest',
			sec: 'No finger loading · walk / mobility',
			load: 'OFF',
			color: 'var(--ink-faint)',
			ex: ['rest'],
		},
	],
	exercises: {
		recruit: {
			name: 'Recruitment Pulls',
			cat: 'RFD / Contact',
			catVar: '--flag',
			what: '1-arm · ~20mm or flat edge',
			spec: '3–5s MAX pull, fast force build · 5s rest · 4 reps/side · 2–3 sets',
			why: [
				"Highest-yield finger stimulus once you're already strong — trains <b>rate of force development</b> and contact strength with very little fatigue.",
				'Tyler Nelson: at high levels, force <b>application</b> matters more than more max force.',
			],
			swaps: [
				'Recruitment pulls (1-arm, flat edge)',
				'Campus-board controlled max touches',
				'Lattice-block one-arm max lifts',
				'Heavy first-move limit attempts off the wall',
			],
		},
		limitboulder: {
			name: 'Limit Bouldering',
			cat: 'Power / Skill',
			catVar: '--flag',
			what: 'Hardest problems · long rests',
			spec: '4–6 hard problems · 3–5 min rest · prioritise crimp / contact moves',
			why: [
				'Where strength becomes climbing. Quality over quantity — rest fully between attempts.',
			],
			swaps: [
				'Limit bouldering (gym/outdoor)',
				'Moonboard / Kilter limit problems',
				'Hard 4×4-style power problems',
				'Outdoor boulder project session',
			],
		},
		pinch: {
			name: 'Pinch Block — Max',
			cat: 'Pinch',
			catVar: '--gold',
			what: 'One thumb-pad-depth block',
			spec: '7–10s lifts · ~90% of 7s max · 5–7 sets · 3 min between sets · 30s between arms',
			why: [
				"Shoulders retracted, arm by side, lift with legs. <b>Never</b> front-facing pinch hangs — De Quervain's risk (López).",
				'Rotate block width across the 8 weeks; go narrower / pads-only in Phase 2.',
			],
			swaps: [
				'Weighted pinch block lifts',
				'Two-hand pinch deadlift on bar',
				'Wide-pinch hangs on a 40°+ board',
				'Rockstar / Tension pinch rail max',
			],
		},
		wrist: {
			name: 'Wrist / Sloper Strength',
			cat: 'Wrist',
			catVar: '--gold',
			what: 'Wrist-wrench / radial lifts',
			spec: 'Hypertrophy: 20–40s to failure @ 65–75% max · 3–5 sets · 2 min rest',
			why: [
				'Builds FCR + wrist stabilisers slopers and compression demand.',
				'Ferrer-Uris 2023: 60mm sloper ≈ half-crimp FDP activation, with <b>better</b> FCR/FDS and lower injury risk.',
			],
			swaps: [
				'Wrist-wrench radial deviation lifts',
				'Big-sloper density hangs (60mm)',
				'Reverse + standard wrist curls (heavy)',
				'Compression board / pinch-sloper system',
			],
		},
		repeaters: {
			name: '7/3 Repeaters',
			cat: 'Endurance / CF',
			catVar: '--gold',
			what: '20mm · half-crimp + open hand',
			spec: '~60% MVC · 7s on / 3s off ×6 = 1 set · 3–4 sets/grip · 2 grips · 3 min rest',
			why: [
				'Builds glycolytic capacity, pump resistance, <b>critical force</b> — your likely real gap given how strong your max is.',
				'Phase 2: drop to 2–3 sets/grip @ ~65–70% to stay snappy for weekends.',
			],
			swaps: [
				'7/3 repeaters (hangboard)',
				'6:10 repeaters (longer recovery)',
				'Critical-force protocol (4s/4s to failure)',
				'On-the-wall lap intervals / boulder 4×4',
			],
		},
		sport: {
			name: 'Sport Climbing / Board Laps',
			cat: 'Endurance / CF',
			catVar: '--gold',
			what: 'Sub-maximal, controlled pump',
			spec: 'Routes or board laps · build a pump but never to failure',
			why: ['Translates the repeater stimulus to real movement and aerobic capacity.'],
			swaps: [
				'Sport routes / auto-belay laps',
				'Board climbing volume (easy angle)',
				'Circuit / ARC traversing 2×15–20 min',
				'Linked boulder problems (4×4)',
			],
		},
		pull: {
			name: 'Heavy Pull Day',
			cat: 'Pull power',
			catVar: '--violet',
			what: 'Weighted pull-ups + OAP work',
			spec: 'Weighted: 4–6 sets ×3–5 reps, hard but clean (~+30–45kg) · OAP: negatives / assisted, 3–4 sets/side',
			why: [
				'On a low-finger-cost day on purpose — pulling power without grinding skin or pulleys.',
				'Phase 2: shift toward lower reps / higher load or more OAP skill work.',
			],
			swaps: [
				'Weighted pull-ups + OAP negatives',
				'One-arm pull-up skill ladder',
				'Frenchies / tempo weighted pulls',
				'Front-lever + weighted pull combo',
			],
		},
		slopdens: {
			name: 'Sloper Density Hangs',
			cat: 'Tissue',
			catVar: '--teal',
			what: 'Bottom edge of a sloper',
			spec: '30–45s · 3 sets · 2 arms · open-hand position',
			why: ["Open-hand tissue work that doesn't tax pulleys — pairs well after the pull day."],
			swaps: [
				'Sloper density hangs',
				'Open-hand 35mm density hangs',
				'Big-rung repeaters (open hand)',
				'No-hang open-hand long holds',
			],
		},
		maxhang: {
			name: 'Max Hangs — Maintenance',
			cat: 'Max strength',
			catVar: '--violet',
			what: 'Short dose · ~10mm edge',
			spec: '3 sets ×10s · leave a 2–3s margin · 3 min rest (López MAW/MED, minimal)',
			why: [
				"You're <b>maintaining</b>, not chasing PRs — your max is near ceiling and extra volume here is mostly injury cost.",
			],
			swaps: [
				'Max hangs 10s (10mm, margin)',
				'MED — bodyweight on smaller edge',
				'MAW — 18–20mm + added weight',
				'No-hang max block lifts (10s)',
			],
		},
		density: {
			name: 'Density Hangs',
			cat: 'Tissue',
			catVar: '--teal',
			what: 'Near-failure long holds',
			spec: '20–40s near failure @ ~70–75% MVC · 5–6 sets · 3 min rest',
			why: [
				'Your main connective-tissue investment. Raises muscle + MTJ stiffness while <b>reducing</b> pathological tendon stiffness — a net more injury-resistant system (Nelson).',
			],
			swaps: [
				'Density hangs (half-crimp)',
				'Density hangs (open hand)',
				'No-hang density block lifts',
				'Long-duration repeaters @ low %',
			],
		},
		abra: {
			name: 'Abrahangs (low-load)',
			cat: 'Tissue',
			catVar: '--teal',
			what: 'AM · 18–22mm · feet on floor',
			spec: '~40% max ("light strain only") · ~10 min total · ~20×10s across grips · ≥6h from hard work',
			why: [
				'Additive to max work for tissue health (Gilmore/Baar 2024). At your strength, keep these genuinely <b>light</b> — err under 40%.',
				'These are training, not rest — drop them <b>first</b> at any tweak.',
			],
			swaps: [
				'Abrahangs (no-hang, feet down)',
				'Light no-hang block holds',
				'Low-% long repeaters',
				'Skip — extra rest if fatigued',
			],
		},
		antag: {
			name: 'Antagonists',
			cat: 'Prehab',
			catVar: '--teal',
			what: '~10 min · elbow + pulley insurance',
			spec: 'Reverse wrist curls 3×15 · band finger extensions 3×20–30 · pronation/supination 3×12 · push-ups/dips',
			why: ['Essential given your flexor dominance — protects elbows and pulleys.'],
			swaps: [
				'Band + dumbbell antagonist set',
				'Rice-bucket + extensor bands',
				'Theraband finger extensions only',
				'Push/pronation circuit',
			],
		},
		perform: {
			name: 'Outdoor / Performance',
			cat: 'Skill',
			catVar: '--flag',
			what: 'Hangboard = warm-up only',
			spec: 'Your hardest real climbing of the week · full warm-up · send mindset',
			why: ['During send windows the hangboard drops to a warm-up tool (Hörst).'],
			swaps: [
				'Outdoor project session',
				'Hard gym performance day',
				'Comp-style flash session',
				'Long multi-boulder outdoor day',
			],
		},
		rest: {
			name: 'Full Rest',
			cat: 'Recovery',
			catVar: '--ink-faint',
			what: 'No finger loading',
			spec: 'Walk · mobility · sleep · eat. Adaptation happens now, not on the wall.',
			why: ['Even at your level the cap is ~3 high-CNS days/week. This is non-negotiable.'],
			swaps: [
				'Complete rest',
				'Light walk + mobility only',
				'Easy aerobic (no grip)',
				'Gentle Abrahangs only if itching to move',
			],
		},
	},
	metrics: [
		{
			id: 'rfd',
			name: 'Rate of Force Dev',
			abbr: 'RFD',
			cat: '--flag',
			unit: '%/100ms',
			desc: 'How fast you reach peak force. Test: max recruitment pull, note time-to-peak feel or device value.',
		},
		{
			id: 'contact',
			name: 'Contact Strength',
			abbr: 'CONTACT',
			cat: '--flag',
			unit: 'kg / edge',
			desc: 'Force you catch instantly on small holds. Test: heaviest 3s recruitment pull on a fixed edge.',
		},
		{
			id: 'cf',
			name: 'Critical Force',
			abbr: 'CF',
			cat: '--gold',
			unit: '% MVC',
			desc: 'Sustainable force floor — your endurance ceiling. Test: repeater protocol to failure.',
		},
		{
			id: 'pinch',
			name: 'Pinch Max',
			abbr: 'PINCH',
			cat: '--gold',
			unit: 'kg / 7s',
			desc: 'Best 7-second pinch-block lift. Test each arm.',
		},
		{
			id: 'pull',
			name: 'Weighted Pull',
			abbr: 'PULL',
			cat: '--violet',
			unit: 'kg added',
			desc: 'Top weighted chin/pull-up for a clean rep.',
		},
		{
			id: 'maxhang',
			name: 'Max Hang',
			abbr: 'MAXHANG',
			cat: '--violet',
			unit: 'kg @ 10mm',
			desc: 'Maintenance benchmark — added weight, 10s, 10mm.',
		},
		{
			id: 'density',
			name: 'Density Hold',
			abbr: 'DENSITY',
			cat: '--teal',
			unit: 'sec @ load',
			desc: 'Longest quality density hold at working load — tissue capacity proxy.',
		},
	],
	quiz: [
		{
			id: 'recovery',
			q: 'How recovered do you feel?',
			a: [
				{ t: 'Fresh & fired up', v: 2 },
				{ t: 'Normal', v: 1 },
				{ t: 'A bit flat', v: 0 },
				{ t: 'Wrecked / sore', v: -2 },
			],
		},
		{
			id: 'fingers',
			q: 'How do your fingers feel?',
			a: [
				{ t: '100% — no niggles', v: 2 },
				{ t: 'Fine, slight stiffness', v: 1 },
				{ t: 'Tender on a knuckle/pulley', v: -2 },
				{ t: 'Sharp pain anywhere', v: -5 },
			],
		},
		{
			id: 'slot',
			q: "What's the slot today?",
			a: [
				{ t: 'Big session, lots of time', v: 2 },
				{ t: 'Standard session', v: 1 },
				{ t: 'Short — 30–45 min', v: 0 },
				{ t: 'Almost no time', v: -1 },
			],
		},
		{
			id: 'skin',
			q: 'Skin & CNS / drive?',
			a: [
				{ t: 'Skin good, feeling sharp', v: 2 },
				{ t: 'Okay', v: 1 },
				{ t: 'Thin skin / low drive', v: -1 },
				{ t: 'Both shot', v: -2 },
			],
		},
	],
	verdicts: {
		rest: {
			title: 'Stop — rest the fingers',
			tag: 'Pain protocol',
			color: 'var(--flag)',
			text: 'Sharp finger pain is a hard stop. <b>No loading today.</b> Pulley injuries are ~60% of finger injuries and driven by pushing through exactly this. If it persists past 3–5 days, get it assessed. Today: gentle mobility, sleep, food.',
			focus: ['REST', 'assess', 'no hangboard'],
		},
		tissue: {
			title: 'Tissue / recovery day',
			tag: 'Low load only',
			color: 'var(--teal)',
			text: "You're under-recovered or carrying a niggle. Run <b>low-load tissue work only</b>: light Abrahangs (well under 40%), antagonists, easy mobility. This is productive — connective tissue is your bottleneck anyway — and it protects the hard days.",
			focus: ['Abrahangs', 'antagonists', 'wrist mobility'],
		},
		moderate: {
			title: 'Moderate — endurance or grip-type',
			tag: 'Quality, not max',
			color: 'var(--gold)',
			text: 'Good enough to train, not to go to your limit. Best picks: <b>7/3 repeaters</b> for critical force, or a <b>pinch / wrist / sloper</b> session. Avoid maximal recruitment and limit bouldering today — save the CNS.',
			focus: ['repeaters', 'pinch', 'sloper', 'critical force'],
		},
		short: {
			title: 'Short & sharp — contact strength',
			tag: 'High value, low volume',
			color: 'var(--flag)',
			text: "You're fresh but short on time. Perfect for <b>recruitment pulls</b> — 2–3 sets trains RFD and contact strength in ~15 min with minimal fatigue. Warm up properly first; quality over quantity.",
			focus: ['recruitment pulls', 'RFD', 'contact strength'],
		},
		green: {
			title: 'Green light — go hard',
			tag: 'Limit / max day',
			color: 'var(--flag)',
			text: 'Fresh, fingers good, time and skin to spend. Run a <b>hard day</b>: recruitment pulls into <b>limit bouldering</b>, or a heavy pull day. Take full rests between maximal efforts. Fuel collagen ~60 min before: 15g collagen + 50mg vit C.',
			focus: ['recruitment pulls', 'limit bouldering', 'heavy pull'],
		},
	},
	phases: {
		phase1: {
			name: 'Phase 1 · Capacity & Tissue Base (Wk 1–4)',
			banner:
				'Build recruitment quality, establish pinch 7s max, higher repeater volume, build pull volume + OAP negatives, full density. Collagen + vit C ~60 min before heaviest finger session.',
			cat: '--gold',
		},
		phase2: {
			name: 'Phase 2 · Expression & Peaking (Wk 5–7)',
			banner:
				'Emphasise contact strength on worse holds; narrower pinch; cut repeater sets to stay powerful; pull shifts to lower-rep/higher-load. Max hangs stay minimal.',
			cat: '--flag',
		},
		deload: {
			name: 'Week 8 · Deload',
			banner:
				"Halve volume AND intensity. Two short hangboard sessions, big margins. Easy climbing only. KEEP light Abrahangs — true unloading costs ~10–20% tendon collagen in days (Baar). Adaptations surface now as fatigue clears. Retest at week's end.",
			cat: '--teal',
		},
	},
	glossary: {
		CNS: 'Central nervous system — the systemic fatigue that caps maximal, high-intensity efforts.',
		RFD: 'Rate of force development — how fast you reach peak force, not just how much.',
		MVC: 'Maximal voluntary contraction — your maximum force on a given grip.',
		MTJ: 'Muscle–tendon junction — where muscle transitions into tendon.',
		OAP: 'One-arm pull-up.',
		FCR: 'Flexor carpi radialis — a wrist flexor on the thumb side.',
		FDP: 'Flexor digitorum profundus — the deep finger flexor that drives crimping.',
		FDS: 'Flexor digitorum superficialis — a superficial finger flexor.',
		CF: 'Critical force — the highest force you can sustain almost indefinitely; your endurance floor.',
		MAW: 'Max Added Weight — a López hangboard protocol: fixed edge, add weight.',
		MED: 'Minimum Edge Depth — a López protocol: bodyweight on a progressively smaller edge.',
		ARC: 'Aerobic Restoration & Capillarity — easy continuous climbing to build an endurance base.',
		"De Quervain's": "De Quervain's tenosynovitis — irritation of the thumb-side wrist tendons.",
	},
};

export default content;
