import type { LocaleContent } from './types';

const content: LocaleContent = {
	days: [
		{
			k: 'Mon',
			label: 'Mon',
			type: 'Limit / Power',
			prime: 'Recruitment pulls → Limit bouldering',
			sec: 'Contact strength / RFD, then hardest problems',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['recruit', 'limitboulder'],
		},
		{
			k: 'Tue',
			label: 'Tue',
			type: 'Pinch / Wrist',
			prime: 'Pinch block + Wrist / Sloper',
			sec: 'Abrahangs AM · antagonists',
			load: 'MOD',
			color: 'var(--gold)',
			ex: ['pinch', 'wrist', 'abra', 'antag'],
		},
		{
			k: 'Wed',
			label: 'Wed',
			type: 'Endurance',
			prime: '7/3 Repeaters → Sport climbing',
			sec: 'Strength-endurance, critical force, pump',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['repeaters', 'sport'],
		},
		{
			k: 'Thu',
			label: 'Thu',
			type: 'Pull',
			prime: 'Heavy pull day + Sloper density',
			sec: 'Weighted pull-ups, OAP · Abrahangs AM',
			load: 'MOD',
			color: 'var(--violet)',
			ex: ['pull', 'slopdens', 'abra', 'antag'],
		},
		{
			k: 'Fri',
			label: 'Fri',
			type: 'Max / Tissue',
			prime: 'Max hangs (maintenance) + Density',
			sec: 'Tissue investment, MTJ density',
			load: 'MOD',
			color: 'var(--teal)',
			ex: ['maxhang', 'density'],
		},
		{
			k: 'Sat',
			label: 'Sat',
			type: 'Performance',
			prime: 'Outdoor / Performance',
			sec: 'Hangboard = warm-up only',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['perform'],
		},
		{
			k: 'Sun',
			label: 'Sun',
			type: 'Rest',
			prime: 'Full rest',
			sec: 'No finger loading · walk / mobility',
			load: 'OFF',
			color: 'var(--ink-faint)',
			ex: ['rest'],
		},
	],
	exercises: {
		recruit: {
			name: 'Recruitment Pulls',
			cat: 'RFD / Contact',
			variants: [
				{
					name: 'Hangboard · 1-arm ~20mm',
					what: '1-arm · ~20mm or flat edge',
					note: 'Fast, explosive max pull.',
					why: [
						"Highest-yield finger stimulus once you're already strong — trains <b>rate of force development</b> and contact strength with very little fatigue.",
						'Tyler Nelson: at high levels, force <b>application</b> matters more than more max force.',
					],
				},
				{
					name: 'Campus-board controlled max touches',
					what: 'Controlled max-reach touches',
					note: 'Precise max touches to a fixed rung — full rest, quality over sloppy campusing.',
					why: ['Same recruitment intent with a controlled catch — quality over sloppy campusing.'],
				},
				{
					name: 'Lattice-block one-arm max lifts',
					what: 'One-arm block pull · ~20mm',
					note: 'Near-max one-arm lift on a block.',
					why: ['Device-measured pulls load precisely and let you track contact force.'],
				},
				{
					name: 'Heavy first-move limit attempts',
					what: 'Hard first moves off the ground',
					note: 'Repeated max attempts at a hard first move · full rest.',
					why: ['Recruitment expressed on real holds — maximal pulls into one hard move.'],
				},
			],
		},
		limitboulder: {
			name: 'Limit Bouldering',
			cat: 'Power / Skill',
			variants: [
				{
					name: 'Hardest problems · long rests',
					what: 'Hardest problems · long rests',
					note: 'Prioritise crimp / contact moves. Quality over quantity.',
					why: [
						'Where strength becomes climbing. Quality over quantity — rest fully between attempts.',
					],
				},
				{
					name: 'Moonboard / Kilter limit problems',
					what: 'Board limit problems',
					note: 'Crimp-heavy board benchmarks.',
					why: ['Standardised holds make limit power repeatable and trackable.'],
				},
				{
					name: 'Hard 4×4-style power problems',
					what: 'Power circuits near limit',
					note: 'Short rest within, long between rounds — power-endurance edge near limit.',
					why: ['Adds a power-endurance edge while staying near limit strength.'],
				},
				{
					name: 'Outdoor boulder project session',
					what: 'Rock project',
					note: 'Full warm-up · work a true project · generous rest between goes.',
					why: ["Real rock recruits power and skill the gym can't replicate."],
				},
			],
		},
		pinch: {
			name: 'Pinch Block',
			cat: 'Pinch',
			variants: [
				{
					name: 'Max — thumb-pad-depth block',
					what: 'One thumb-pad-depth block',
					note: 'Shoulders retracted, arm by side, lift with legs · ~30s between arms.',
					why: [
						"Shoulders retracted, arm by side, lift with legs. <b>Never</b> front-facing pinch hangs — De Quervain's risk (López).",
						'Rotate block width across the 8 weeks; go narrower / pads-only in Phase 2.',
					],
				},
				{
					name: 'Two-hand pinch deadlift on bar',
					what: 'Two-hand pinch off the floor',
					note: 'Near-max two-hand pinch lift off the floor.',
					why: ['Heavier loading with two hands — great for raw pinch strength.'],
				},
				{
					name: 'Wide-pinch hangs on a 40°+ board',
					what: 'Wide pinches on a steep board',
					note: 'Hold / move on wide pinches · full rest.',
					why: ['Trains thumb opposition in a climbing-specific position.'],
				},
				{
					name: 'Rockstar / Tension pinch rail max',
					what: 'Commercial pinch rail',
					note: 'Max lifts per width; rotate widths.',
					why: ['A repeatable pinch rail makes loading and tracking easy.'],
				},
			],
		},
		wrist: {
			name: 'Wrist / Sloper Strength',
			cat: 'Wrist / Slopers',
			variants: [
				{
					name: 'Wrist-wrench / radial lifts',
					what: 'Wrist-wrench / radial lifts',
					note: 'To failure · hypertrophy dose for FCR + wrist stabilisers.',
					why: [
						'Builds FCR + wrist stabilisers for slopers and compression demand.',
						'Ferrer-Uris 2023: 60mm sloper ≈ half-crimp FDP activation, with <b>better</b> FCR/FDS and lower injury risk.',
					],
				},
				{
					name: 'Big-sloper density hangs (60mm)',
					what: '60mm sloper · open hand',
					note: '2 arms · open-hand.',
					why: ['Loads the wrist + FCR in a sloper position with low pulley cost.'],
				},
				{
					name: 'Reverse + standard wrist curls (heavy)',
					what: 'Loaded wrist curls',
					note: 'Heavy, scalable wrist hypertrophy.',
					why: ['Direct, scalable wrist hypertrophy for elbow and wrist resilience.'],
				},
				{
					name: 'Compression board / pinch-sloper system',
					what: 'Compression holds',
					note: 'Holds / moves on compression features.',
					why: ['Trains wrist stability under compression demand.'],
				},
			],
		},
		repeaters: {
			name: 'Repeaters',
			cat: 'Endurance / CF',
			variants: [
				{
					name: '7/3 · 20mm half-crimp + open hand',
					what: '20mm · half-crimp + open hand',
					note: '2 grips: half-crimp + open hand.',
					why: [
						'Builds glycolytic capacity, pump resistance, <b>critical force</b> — your likely real gap given how strong your max is.',
						'Phase 2: drop to 2–3 sets/grip @ ~65–70% to stay snappy for weekends.',
					],
				},
				{
					name: '6:10 (longer recovery)',
					what: '6s on / 10s off',
					note: 'Longer rests bias aerobic capacity over glycolytic stress.',
					why: ['Longer rests bias aerobic capacity over glycolytic stress.'],
				},
				{
					name: 'Critical-force protocol (4s/4s to failure)',
					what: '4s on / 4s off to failure',
					note: 'On/off to failure — until force settles to steady state.',
					why: ['Directly probes and builds your <b>critical force</b> floor.'],
				},
				{
					name: 'On-the-wall lap intervals / boulder 4×4',
					what: 'Wall laps / 4×4',
					note: 'Sub-limit · build a pump, stop before failure.',
					why: ['Transfers repeater capacity to real movement.'],
				},
			],
		},
		sport: {
			name: 'Sport Climbing',
			cat: 'Endurance / CF',
			variants: [
				{
					name: 'Board laps · controlled pump',
					what: 'Sub-maximal, controlled pump',
					note: 'Routes or board laps · build a pump but never to failure.',
					why: ['Translates the repeater stimulus to real movement and aerobic capacity.'],
				},
				{
					name: 'Sport routes / auto-belay laps',
					what: 'Route mileage',
					note: 'Continuous easy–moderate routes · rest as needed.',
					why: ['Aerobic base on real routes — keep the effort moderate.'],
				},
				{
					name: 'Board climbing volume (easy angle)',
					what: 'Easy-angle volume',
					note: 'Many easy board problems · ~20–30 min steady pump.',
					why: ['High-volume movement quality and capillarity.'],
				},
				{
					name: 'Circuit / ARC traversing 2×15–20 min',
					what: 'ARC traverse',
					note: '2×15–20 min continuous easy traversing (<b>ARC</b>).',
					why: ['Classic <b>ARC</b> work for endurance base and recovery.'],
				},
			],
		},
		pull: {
			name: 'Pull Strength',
			cat: 'Pull power',
			variants: [
				{
					name: 'Heavy weighted pull-ups + OAP',
					what: 'Weighted pull-ups + OAP work',
					note: 'Hard but clean · OAP negatives / assisted 3–4 sets/side.',
					why: [
						'On a low-finger-cost day on purpose — pulling power without grinding skin or pulleys.',
						'Phase 2: shift toward lower reps / higher load or more OAP skill work.',
					],
				},
				{
					name: 'One-arm pull-up skill ladder',
					what: 'OAP progressions',
					note: 'Assisted → negatives → singles · full rest.',
					why: ['Builds toward the one-arm pull with high neural demand and low finger cost.'],
				},
				{
					name: 'Frenchies / tempo weighted pulls',
					what: 'Tempo + isometric holds',
					note: 'Frenchies (pause 90° / full lock) or tempo weighted pulls.',
					why: ['Adds time-under-tension and lock-off strength.'],
				},
				{
					name: 'Front-lever + weighted pull combo',
					what: 'Front-lever + pull',
					note: 'Front-lever progressions + weighted pulls.',
					why: ['Core-driven pulling power for steep terrain.'],
				},
			],
		},
		slopdens: {
			name: 'Sloper Density',
			cat: 'Tissue',
			variants: [
				{
					name: 'Sloper bottom-edge hangs',
					what: 'Bottom edge of a sloper',
					note: '2 arms · open-hand position.',
					why: ["Open-hand tissue work that doesn't tax pulleys — pairs well after the pull day."],
				},
				{
					name: 'Open-hand 35mm density hangs',
					what: '35mm · open hand',
					note: '2 arms · open hand · near-sub-max.',
					why: ['Open-hand tissue load on a defined edge.'],
				},
				{
					name: 'Big-rung repeaters (open hand)',
					what: 'Big rung · open hand',
					note: 'Long repeaters on a big rung.',
					why: ['Tissue volume with minimal pulley stress.'],
				},
				{
					name: 'No-hang open-hand long holds',
					what: 'No-hang block · open hand',
					note: '2 arms · no-hang block.',
					why: ['Easy to load and pulley-friendly — great for tweaky days.'],
				},
			],
		},
		maxhang: {
			name: 'Max Hangs',
			cat: 'Max strength',
			variants: [
				{
					name: 'Maintenance · ~10mm',
					what: 'Short dose · ~10mm edge',
					note: 'Leave a 2–3s margin (López <b>MAW</b>/<b>MED</b>, minimal).',
					why: [
						"You're <b>maintaining</b>, not chasing PRs — your max is near ceiling and extra volume here is mostly injury cost.",
					],
				},
				{
					name: 'MED — bodyweight on smaller edge',
					what: 'Minimum edge depth · bodyweight',
					note: 'Smallest manageable edge (López <b>MED</b>).',
					why: ['López <b>MED</b>: shrink the edge instead of adding weight.'],
				},
				{
					name: 'MAW — 18–20mm + added weight',
					what: 'Max added weight · 18–20mm',
					note: '2–3s margin (López <b>MAW</b>).',
					why: ['López <b>MAW</b>: add weight on a friendlier edge.'],
				},
				{
					name: 'No-hang max block lifts (10s)',
					what: 'No-hang block max',
					note: 'Near-max block lifts.',
					why: ['Pulley-friendly max strength you can load precisely.'],
				},
			],
		},
		density: {
			name: 'Density Hangs',
			cat: 'Tissue',
			variants: [
				{
					name: 'Half-crimp · near failure',
					what: 'Near-failure long holds',
					note: 'Near failure · half-crimp.',
					why: [
						'Your main connective-tissue investment. Raises muscle + MTJ stiffness while <b>reducing</b> pathological tendon stiffness — a net more injury-resistant system (Nelson).',
					],
				},
				{
					name: 'Open hand · long holds',
					what: 'Open hand · long holds',
					note: 'Near failure · open hand.',
					why: ['Same tissue stimulus shifted to the open-hand position.'],
				},
				{
					name: 'No-hang density block lifts',
					what: 'No-hang block',
					note: 'Near failure · no-hang block.',
					why: ['Pulley-friendly density loading.'],
				},
				{
					name: 'Long-duration repeaters @ low %',
					what: 'Low-% long repeaters',
					note: 'Long on/off repeaters · several sets.',
					why: ['Accumulates tissue time-under-load with low peak force.'],
				},
			],
		},
		abra: {
			name: 'Abrahangs',
			cat: 'Tissue',
			variants: [
				{
					name: 'Hangboard · 2 hands',
					what: 'Wall hangboard · both hands · 18–22mm',
					note: '"Light strain only" · ~10 min · across grips · ≥6h from hard work.',
					tool: 'Hangboard · 2 hands',
					speed: 'Standard',
					why: [
						'Additive to max work for tissue health (Gilmore/Baar 2024). At your strength, keep these genuinely <b>light</b> — err under 40%.',
						'These are training, not rest — drop them <b>first</b> at any tweak.',
					],
				},
				{
					name: 'Block · 1 hand',
					what: 'No-hang pin/block · one hand at a time',
					note: 'One arm at a time on a loading pin · switch hands each rep · keep it light.',
					tool: 'Block · 1 hand',
					speed: 'Standard',
					why: ['Per-hand no-hang loading — precise and easy to keep well under 40%.'],
				},
				{
					name: 'Hangboard · 2 hands · fast',
					what: 'abrafast · 15s on / 20s off · 13 rounds',
					note: 'Faster abrahang: longer holds, fewer rounds.',
					tool: 'Hangboard · 2 hands',
					speed: 'Fast',
					why: ['Same light tissue stimulus, quicker to fit in.'],
				},
				{
					name: 'Block · 1 hand · fast',
					what: 'abrafast 1-handed · alternate hands each rep',
					note: 'Switch hands each rep (2s) · 2 cycles.',
					tool: 'Block · 1 hand',
					speed: 'Fast',
					why: ['Per-hand fast version — alternate hands, minimal rest.'],
				},
			],
		},
		antag: {
			name: 'Antagonists',
			cat: 'Prehab',
			variants: [
				{
					name: 'Full circuit',
					what: '~10 min · elbow + pulley insurance',
					note: 'Reverse wrist curls 3×15 · band finger extensions 3×20–30 · pronation/supination 3×12 · push-ups/dips.',
					why: ['Essential given your flexor dominance — protects elbows and pulleys.'],
				},
				{
					name: 'Rice-bucket + extensor bands',
					what: 'Rice bucket + bands',
					note: '~5–8 min · rice-bucket + band finger extensions.',
					why: ['Low-effort extensor and forearm endurance work.'],
				},
				{
					name: 'Theraband finger extensions only',
					what: 'Band extensions',
					note: 'Daily-friendly extensor balance.',
					why: ['Minimal-dose extensor balance when short on time.'],
				},
				{
					name: 'Push/pronation circuit',
					what: 'Push + pronation',
					note: '~8–10 min · push-ups / dips + pronation/supination.',
					why: ['Pushing + rotation balance for shoulders and elbows.'],
				},
			],
		},
		perform: {
			name: 'Performance',
			cat: 'Skill',
			variants: [
				{
					name: 'Outdoor send day',
					what: 'Hangboard = warm-up only',
					note: 'Your hardest real climbing of the week · full warm-up · send mindset.',
					why: ['During send windows the hangboard drops to a warm-up tool (Hörst).'],
				},
				{
					name: 'Hard gym performance day',
					what: 'Gym performance',
					note: 'Hardest gym climbing · full warm-up · real send attempts.',
					why: ["A performance stimulus when rock isn't an option."],
				},
				{
					name: 'Comp-style flash session',
					what: 'Flash session',
					note: 'Onsight / flash a spread of problems · short prep per problem.',
					why: ['Trains reading and first-go execution.'],
				},
				{
					name: 'Long multi-boulder outdoor day',
					what: 'Volume on rock',
					note: 'Many boulders across the day · manage skin and energy.',
					why: ['High-quality outdoor mileage and skill.'],
				},
			],
		},
		rest: {
			name: 'Rest',
			cat: 'Recovery',
			variants: [
				{
					name: 'Full rest',
					what: 'No finger loading',
					note: 'Walk · mobility · sleep · eat. Adaptation happens now, not on the wall.',
					why: ['Even at your level the cap is ~3 high-CNS days/week. This is non-negotiable.'],
				},
				{
					name: 'Light walk + mobility only',
					what: 'Walk + mobility',
					note: 'Easy walk + 10–15 min mobility · no grip load.',
					why: ["Active recovery that doesn't tax the fingers."],
				},
				{
					name: 'Easy aerobic (no grip)',
					what: 'Easy aerobic',
					note: '20–40 min easy cardio · no grip.',
					why: ['Promotes recovery and aerobic base without finger load.'],
				},
				{
					name: 'Gentle Abrahangs only if itching to move',
					what: 'Gentle Abrahangs',
					note: 'Very light Abrahangs only if you must.',
					why: ['The most you should do on a rest day, and only if fresh.'],
				},
			],
		},
	},
	metrics: [
		{
			id: 'rfd',
			name: 'Rate of Force Dev',
			abbr: 'RFD',
			cat: '--flag',
			unit: '%/100ms',
			desc: 'How fast you reach peak force. Test: max recruitment pull, note time-to-peak feel or device value.',
		},
		{
			id: 'contact',
			name: 'Contact Strength',
			abbr: 'CONTACT',
			cat: '--flag',
			unit: 'kg / edge',
			desc: 'Force you catch instantly on small holds. Test: heaviest 3s recruitment pull on a fixed edge.',
		},
		{
			id: 'cf',
			name: 'Critical Force',
			abbr: 'CF',
			cat: '--gold',
			unit: '% MVC',
			desc: 'Sustainable force floor — your endurance ceiling. Test: repeater protocol to failure.',
		},
		{
			id: 'pinch',
			name: 'Pinch Max',
			abbr: 'PINCH',
			cat: '--gold',
			unit: 'kg / 7s',
			desc: 'Best 7-second lift on an ~80mm pinch block, added weight. Test each arm.',
		},
		{
			id: 'pull',
			name: 'Weighted Pull',
			abbr: 'PULL',
			cat: '--violet',
			unit: 'kg added',
			desc: 'Top weighted chin/pull-up for a clean rep.',
		},
		{
			id: 'maxhang',
			name: 'Max Hang',
			abbr: 'MAXHANG',
			cat: '--violet',
			unit: 'kg @ 20mm',
			desc: 'Standard benchmark — max added weight, 10s, 20mm edge.',
		},
		{
			id: 'density',
			name: 'Density Hold',
			abbr: 'DENSITY',
			cat: '--teal',
			unit: 'sec @ load',
			desc: 'Longest quality density hold at working load — tissue capacity proxy.',
		},
		{
			id: 'bodyweight',
			name: 'Bodyweight',
			abbr: 'BW',
			cat: '--ink-faint',
			unit: 'kg',
			desc: 'Log this often (ideally daily) — it anchors the % bodyweight strength estimates.',
		},
		{
			id: 'boulder',
			name: 'Boulder Grade',
			abbr: 'BOULDER',
			cat: '--flag',
			unit: 'V-scale',
			desc: 'Your hardest clean boulder (V-scale) — the on-the-wall expression of strength.',
		},
		{
			id: 'route',
			name: 'Route Grade',
			abbr: 'ROUTE',
			cat: '--violet',
			unit: 'French',
			desc: 'Your hardest redpoint route (French) — endurance and skill on the wall.',
		},
	],
	quiz: [
		{
			id: 'sleep',
			q: 'How did you sleep?',
			why: 'Sleep is the single strongest driver of recovery and adaptation — short or broken sleep blunts output and raises injury risk.',
			study: 'sleep',
			a: [
				{ t: 'Great — rested', v: 10 },
				{ t: 'OK', v: 7 },
				{ t: 'Poor / short', v: 3 },
				{ t: 'Barely slept', v: 0 },
			],
		},
		{
			id: 'fatigue',
			q: 'How recovered do you feel?',
			why: 'Perceived recovery tracks accumulated fatigue and flags overreaching before performance drops.',
			study: 'prs',
			a: [
				{ t: 'Fresh & fired up', v: 10 },
				{ t: 'Normal', v: 7 },
				{ t: 'A bit flat', v: 4 },
				{ t: 'Wrecked', v: 0 },
			],
		},
		{
			id: 'soreness',
			q: 'Muscle soreness?',
			why: "Lingering soreness means tissue hasn't recovered — loading it raises strain risk and dampens force output.",
			study: 'hooper',
			a: [
				{ t: 'None', v: 10 },
				{ t: 'Mild', v: 7 },
				{ t: 'Moderate', v: 3 },
				{ t: 'Severe', v: 0 },
			],
		},
		{
			id: 'body',
			q: 'Anything hurting today?',
			why: 'Climbing injuries cluster in the fingers, elbows and shoulders — a sore joint changes what you train, not just how hard.',
			a: [
				{ t: 'Nothing', v: 0 },
				{ t: 'Fingers', v: 1 },
				{ t: 'Elbow', v: 2 },
				{ t: 'Shoulder', v: 3 },
				{ t: 'Wrist', v: 4 },
			],
		},
		{
			id: 'illness',
			q: 'Feeling sick at all?',
			why: 'The "neck check": symptoms below the neck (fever, chest, body aches) mean no training — loading a system already fighting illness backfires and, with fever, even raises cardiac risk. Above-the-neck sniffles → keep it easy.',
			study: 'illness',
			a: [
				{ t: 'Feel fine', v: 0 },
				{ t: 'Mild — above the neck', v: 1 },
				{ t: 'Unwell — fever / body aches', v: 2 },
			],
		},
		{
			id: 'time',
			q: 'Time for today?',
			why: 'Time sets the format — a short slot can still be high-value (recruitment), but rules out high-volume work.',
			a: [
				{ t: 'Full session', v: 10 },
				{ t: 'Standard', v: 7 },
				{ t: 'Short — 30–45 min', v: 3 },
				{ t: 'Tight — under 30', v: 0 },
			],
		},
		{
			id: 'severity',
			followup: true,
			q: 'How does it feel?',
			why: 'Stiffness is safe to train around, tenderness means back off, sharp pain is a stop — severity sets the cap.',
			a: [
				{ t: 'Just stiff', v: 0 },
				{ t: 'Tender', v: 1 },
				{ t: 'Painful', v: 2 },
				{ t: 'Sharp', v: 3 },
			],
		},
		{
			id: 'stress',
			followup: true,
			q: 'Life stress right now?',
			why: 'Psychological stress slows recovery and raises injury risk independent of training — high stress argues for a lighter day.',
			study: 'hooper',
			a: [
				{ t: 'Low / calm', v: 10 },
				{ t: 'Some', v: 6 },
				{ t: 'High', v: 2 },
			],
		},
		{
			id: 'mood',
			followup: true,
			q: 'Motivation & drive?',
			why: 'Low motivation predicts poor session quality and is part of validated wellness monitoring — a cue to train easy, not hard.',
			study: 'hooper',
			a: [
				{ t: 'Keen', v: 10 },
				{ t: 'Normal', v: 6 },
				{ t: 'Flat', v: 3 },
				{ t: 'Dreading it', v: 0 },
			],
		},
		{
			id: 'skin',
			followup: true,
			q: 'How is your skin?',
			why: 'Skin caps a hard crimp/board day no matter how fresh you are — climbing on raw skin just costs more days.',
			a: [
				{ t: 'Solid', v: 10 },
				{ t: 'Thin / worn', v: 4 },
				{ t: 'Split or raw', v: 0 },
			],
		},
	],
	verdicts: {
		rest: {
			title: 'Stop — full rest today',
			tag: 'Hard stop',
			color: 'var(--flag)',
			text: "A hard stop today — <b>no loading.</b> If it's sharp finger pain, that's often an A2/A4 pulley (~60% of finger injuries) and pushing through is exactly what turns a niggle into months off — get it assessed if it lasts past 3–5 days. If you're unwell with fever or body aches, training a system already fighting illness sets you back further (and with fever, stresses the heart). Today: sleep, food, gentle mobility; reassess tomorrow.",
			focus: ['REST', 'recover', 'reassess'],
		},
		tissue: {
			title: 'Tissue / recovery day',
			tag: 'Low load only',
			color: 'var(--teal)',
			text: "You're under-recovered or carrying a niggle. Run <b>low-load tissue work only</b>: light Abrahangs (well under 40%), antagonists, easy mobility. This is productive — connective tissue is your bottleneck anyway — and it protects the hard days.",
			focus: ['Abrahangs', 'antagonists', 'wrist mobility'],
		},
		moderate: {
			title: 'Moderate — endurance or grip-type',
			tag: 'Quality, not max',
			color: 'var(--gold)',
			text: 'Good enough to train, not to go to your limit. Best picks: <b>7/3 repeaters</b> for critical force, or a <b>pinch / wrist / sloper</b> session. Avoid maximal recruitment and limit bouldering today — save the CNS.',
			focus: ['repeaters', 'pinch', 'sloper', 'critical force'],
		},
		short: {
			title: 'Short & sharp — contact strength',
			tag: 'High value, low volume',
			color: 'var(--flag)',
			text: "You're fresh but short on time. Perfect for <b>recruitment pulls</b> — 2–3 sets trains RFD and contact strength in ~15 min with minimal fatigue. Warm up properly first; quality over quantity.",
			focus: ['recruitment pulls', 'RFD', 'contact strength'],
		},
		green: {
			title: 'Green light — go hard',
			tag: 'Limit / max day',
			color: 'var(--flag)',
			text: 'Fresh, fingers good, time and skin to spend. Run a <b>hard day</b>: recruitment pulls into <b>limit bouldering</b>, or a heavy pull day. Take full rests between maximal efforts. Fuel collagen ~60 min before: 15g collagen + 50mg vit C.',
			focus: ['recruitment pulls', 'limit bouldering', 'heavy pull'],
		},
	},
	flags: {
		finger_pain: {
			title: 'Sharp finger pain',
			text: 'Stop loading the fingers today — sharp pain (often an <b>A2/A4 pulley</b>) needs rest, not training. Ice if swollen; if it is still sharp in 3–5 days, get it assessed. Start a structured finger rehab rather than pushing through.',
			focus: ['no hangboard', 'assess', 'rehab'],
		},
		finger_tender: {
			title: 'Tender finger',
			text: 'A tender knuckle or pulley is an early warning. Skip max hangs and crimping; keep it to <b>low-load Abrahangs (under ~40%)</b> and open-hand. A few easy days now prevent weeks off later.',
			focus: ['low load', 'open-hand', 'no crimp'],
		},
		elbow_pain: {
			title: 'Elbow pain',
			text: "Climber's / golfer's elbow flares with pulling and gripping. Cut pulling volume to near zero today; do pain-free <b>wrist eccentrics</b> and light isometrics. Consider an elbow rehab block.",
			focus: ['no hard pulls', 'eccentrics', 'rehab'],
		},
		elbow_niggle: {
			title: 'Elbow niggle',
			text: "Early elbow tendinopathy. Keep pulling <b>submaximal</b> and add light wrist/forearm eccentrics. Don't chase PRs on pull-type work today.",
			focus: ['submax pulls', 'eccentrics'],
		},
		shoulder_pain: {
			title: 'Shoulder pain',
			text: 'A painful shoulder plus overhead load is a bad mix. Avoid max pulls, dynos and deep lock-offs. Do <b>scapular and rotator-cuff prehab</b>; consider a shoulder rehab block.',
			focus: ['no dynos', 'cuff prehab', 'rehab'],
		},
		shoulder_niggle: {
			title: 'Shoulder niggle',
			text: 'Add scapular control and rotator-cuff work; keep pressing/pulling controlled and pain-free. Warm the shoulder thoroughly before any hard move.',
			focus: ['scap control', 'cuff', 'warm up'],
		},
		skin: {
			title: 'Skin is worn',
			text: 'Thin or split skin will not hold up to crimps and rough holds. File flappers, tape splits, and pick <b>juggy or non-finger</b> work today. Pushing on raw skin just costs more days.',
			focus: ['tape', 'jugs', 'antagonists'],
		},
		wrist_pain: {
			title: 'Wrist pain',
			text: 'Wrist pain (often pinch / sloper loading or dorsal impingement) needs offloading. Avoid loaded wrist extension and pinch today; keep <b>pain-free isometrics</b> and mobility. Consider a wrist rehab block.',
			focus: ['no pinch', 'isometrics', 'rehab'],
		},
		wrist_niggle: {
			title: 'Wrist niggle',
			text: 'Keep wrist loading <b>pain-free</b> and add light wrist isometrics and mobility; avoid end-range loaded positions and hard pinch today.',
			focus: ['pain-free', 'isometrics', 'mobility'],
		},
		acwr_spike: {
			title: 'Training-load spike',
			text: 'Your last 7 days are well above your 4-week norm (<b>ACWR &gt; 1.5</b>) — the range linked to higher injury risk. Hold intensity at moderate and let the load settle before the next hard push.',
			focus: ['ease off', 'moderate', 'recover'],
		},
		acwr_high: {
			title: 'Load trending up',
			text: "You're loading above your comfortable range. Keep an eye on fatigue and resist adding more hard volume this week.",
			focus: ['watch load', 'hold volume'],
		},
		acwr_low: {
			title: 'Detraining risk',
			text: 'Recent load is well below your norm. If you feel healthy, it is safe to <b>build back up gradually</b> — small weekly increases beat a sudden spike.',
			focus: ['build back', 'gradual'],
		},
		readiness_declining: {
			title: 'Readiness trending down',
			text: 'Your readiness has slid over the last few days — a sign of <b>accumulating fatigue</b>. Hold today to moderate or easier and bank a proper recovery day soon; pushing through a downward trend is how overreaching becomes overtraining.',
			focus: ['back off', 'recover', 'sleep'],
		},
		below_baseline: {
			title: 'Below your usual',
			text: "Today's readiness is well under your personal norm. Treat it as a real signal — bias toward <b>quality over load</b> and check sleep, food and stress.",
			focus: ['quality', 'watch fatigue'],
		},
		monotony_high: {
			title: 'Training too monotonous',
			text: 'Your last 7 days are <b>samey</b> — similar load every day with no real easy days (high <b>training monotony</b>, Foster). It is the day-to-day variation that lets you adapt; without it, strain accumulates. Make today clearly easier (or rest) so the week has a hard/easy contrast.',
			focus: ['vary load', 'easy day', 'recover'],
		},
		illness_systemic: {
			title: 'Unwell — do not train',
			text: 'Fever or below-the-neck symptoms (chest, body aches, gut) are a <b>hard stop</b>. Training while your body is fighting an infection deepens the hole, and exercising with a fever carries a real risk of <b>myocarditis</b>. Rest, hydrate, sleep. Wait until you are symptom-free and fever-free for 24h, then ease back in.',
			focus: ['no training', 'hydrate', 'sleep'],
		},
		illness_mild: {
			title: 'Mild cold — keep it easy',
			text: 'Above-the-neck only (runny nose, light sore throat, no fever) is generally OK to train <b>easy</b> — keep intensity moderate, cut the volume, and stop if symptoms drop below the neck or a fever appears. Skip max efforts; favour movement quality.',
			focus: ['easy only', 'cut volume', 'monitor'],
		},
		probe_low: {
			title: 'Strength down — fatigued',
			text: "Your max pull is well below your baseline — a sign of real <b>neuromuscular fatigue</b>, whatever the scales say in your head. Treat today as recovery: <b>tissue work only</b>, no max or near-max loading. Force usually rebounds within a day or two once you've recovered.",
			focus: ['recovery', 'no max', 'tissue'],
		},
		probe_fatigued: {
			title: 'Strength slightly down',
			text: 'Your max pull is a touch under baseline — some accumulated fatigue. Hold intensity at <b>moderate</b>: train quality, skip true limit work, and let the nervous system catch up.',
			focus: ['moderate', 'quality', 'no limit'],
		},
		probe_fresh: {
			title: 'Strength on form',
			text: 'Your max pull is at or above baseline — the nervous system is <b>primed</b>. If nothing else is holding you back, this is a green light for hard, high-quality efforts.',
			focus: ['primed', 'go hard'],
		},
	},
	deep: {
		fingers: {
			title: 'Finger / pulley self-check',
			intro:
				'A short screen for finger, pulley and flexor-tendon load tolerance. Answer for the worst-affected finger over the past week.',
			source: 'Modelled on VISA-C (climbing finger / hand / wrist)',
			url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12488532/',
			questions: [
				{
					id: 'stiff',
					q: 'Morning stiffness in the finger?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Eases in a few minutes', v: 7 },
						{ t: '10–30 min', v: 4 },
						{ t: 'Most of the day', v: 0 },
					],
				},
				{
					id: 'crimp',
					q: 'Pain when you load a small edge / crimp hard?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild, warms up', v: 6 },
						{ t: 'Moderate, limits effort', v: 3 },
						{ t: 'Sharp — cannot', v: 0 },
					],
				},
				{
					id: 'after',
					q: 'Pain after a hard finger session?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Gone by next morning', v: 6 },
						{ t: 'Lingers a day', v: 3 },
						{ t: 'Several days', v: 0 },
					],
				},
				{
					id: 'edges',
					q: 'Can you hang / load small edges?',
					a: [
						{ t: 'Fully', v: 10 },
						{ t: 'Somewhat reduced', v: 6 },
						{ t: 'Very limited', v: 3 },
						{ t: 'Not at all', v: 0 },
					],
				},
				{
					id: 'swell',
					q: 'Swelling or thickening at the joint / pulley?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Slight', v: 6 },
						{ t: 'Clear', v: 3 },
						{ t: 'Marked / bowstringing', v: 0 },
					],
				},
				{
					id: 'climb',
					q: 'Climbing right now?',
					a: [
						{ t: 'Full, no restriction', v: 10 },
						{ t: 'Training but modified', v: 7 },
						{ t: 'Easy only', v: 3 },
						{ t: 'Not climbing', v: 0 },
					],
				},
			],
		},
		elbow: {
			title: 'Elbow self-check',
			intro:
				"A short screen for elbow tendinopathy (climber's / golfer's or tennis elbow). Answer for the worst elbow over the past week.",
			source: 'Modelled on the PRTEE (lateral elbow tendinopathy)',
			url: 'https://pubmed.ncbi.nlm.nih.gov/17254903/',
			questions: [
				{
					id: 'rest',
					q: 'Elbow pain at rest?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'grip',
					q: 'Pain with hard pulling or gripping?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'carry',
					q: 'Pain lifting or carrying something heavy?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'weak',
					q: 'Grip feels weak or unreliable?',
					a: [
						{ t: 'No', v: 10 },
						{ t: 'A little', v: 6 },
						{ t: 'Noticeably', v: 3 },
						{ t: 'Very weak', v: 0 },
					],
				},
				{
					id: 'pull',
					q: 'Can you do pull-type training?',
					a: [
						{ t: 'Fully', v: 10 },
						{ t: 'Reduced', v: 6 },
						{ t: 'Light only', v: 3 },
						{ t: 'None', v: 0 },
					],
				},
				{
					id: 'after',
					q: 'Pain after climbing / training?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Settles by next day', v: 6 },
						{ t: 'Lingers a day or more', v: 3 },
						{ t: 'Days', v: 0 },
					],
				},
			],
		},
		shoulder: {
			title: 'Shoulder self-check',
			intro:
				'A short screen for shoulder pain and function. Answer for the worst shoulder over the past week.',
			source: 'Modelled on the SPADI (Shoulder Pain & Disability Index)',
			url: 'https://www.physio-pedia.com/Shoulder_Pain_and_Disability_Index_(SPADI)',
			questions: [
				{
					id: 'worst',
					q: 'Shoulder pain at its worst?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'lie',
					q: 'Pain lying on it?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'overhead',
					q: 'Pain reaching overhead?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Severe', v: 0 },
					],
				},
				{
					id: 'reach',
					q: 'Difficulty reaching or locking off overhead?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'A little', v: 6 },
						{ t: 'A lot', v: 3 },
						{ t: 'Unable', v: 0 },
					],
				},
				{
					id: 'press',
					q: 'Can you press / pull overhead in training?',
					a: [
						{ t: 'Fully', v: 10 },
						{ t: 'Reduced', v: 6 },
						{ t: 'Light only', v: 3 },
						{ t: 'None', v: 0 },
					],
				},
				{
					id: 'climb',
					q: 'Pain on dynamic / powerful moves?',
					a: [
						{ t: 'None', v: 10 },
						{ t: 'Mild', v: 6 },
						{ t: 'Moderate', v: 3 },
						{ t: 'Cannot do them', v: 0 },
					],
				},
			],
		},
	},
	phases: {
		phase1: {
			name: 'Phase 1 · Capacity & Tissue Base (Wk 1–4)',
			banner:
				'Build recruitment quality, establish pinch 7s max, higher repeater volume, build pull volume + OAP negatives, full density. Collagen + vit C ~60 min before heaviest finger session.',
			cat: '--gold',
		},
		phase2: {
			name: 'Phase 2 · Expression & Peaking (Wk 5–7)',
			banner:
				'Emphasise contact strength on worse holds; narrower pinch; cut repeater sets to stay powerful; pull shifts to lower-rep/higher-load. Max hangs stay minimal.',
			cat: '--flag',
		},
		deload: {
			name: 'Week 8 · Deload',
			banner:
				"Halve volume AND intensity. Two short hangboard sessions, big margins. Easy climbing only. KEEP light Abrahangs — true unloading costs ~10–20% tendon collagen in days (Baar). Adaptations surface now as fatigue clears. Retest at week's end.",
			cat: '--teal',
		},
	},
	glossary: {
		CNS: 'Central nervous system — the systemic fatigue that caps maximal, high-intensity efforts.',
		RFD: 'Rate of force development — how fast you reach peak force, not just how much.',
		MVC: 'Maximal voluntary contraction — your maximum force on a given grip.',
		MTJ: 'Muscle–tendon junction — where muscle transitions into tendon.',
		OAP: 'One-arm pull-up.',
		FCR: 'Flexor carpi radialis — a wrist flexor on the thumb side.',
		FDP: 'Flexor digitorum profundus — the deep finger flexor that drives crimping.',
		FDS: 'Flexor digitorum superficialis — a superficial finger flexor.',
		CF: 'Critical force — the highest force you can sustain almost indefinitely; your endurance floor.',
		MAW: 'Max Added Weight — a López hangboard protocol: fixed edge, add weight.',
		MED: 'Minimum Edge Depth — a López protocol: bodyweight on a progressively smaller edge.',
		ARC: 'Aerobic Restoration & Capillarity — easy continuous climbing to build an endurance base.',
		"De Quervain's": "De Quervain's tenosynovitis — irritation of the thumb-side wrist tendons.",
	},
};

export default content;
