import type { LocaleContent } from './types';

const content: LocaleContent = {
	days: [
		{
			k: 'Mon',
			label: 'Mon',
			type: 'Limit / Power',
			prime: 'Recruitment pulls → Limit bouldering',
			sec: 'Contact strength / RFD, then hardest problems',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['recruit', 'limitboulder'],
		},
		{
			k: 'Tue',
			label: 'Tue',
			type: 'Pinch / Wrist',
			prime: 'Pinch block + Wrist / Sloper',
			sec: 'Abrahangs AM · antagonists',
			load: 'MOD',
			color: 'var(--gold)',
			ex: ['pinch', 'wrist', 'abra', 'antag'],
		},
		{
			k: 'Wed',
			label: 'Wed',
			type: 'Endurance',
			prime: '7/3 Repeaters → Sport climbing',
			sec: 'Strength-endurance, critical force, pump',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['repeaters', 'sport'],
		},
		{
			k: 'Thu',
			label: 'Thu',
			type: 'Pull',
			prime: 'Heavy pull day + Sloper density',
			sec: 'Weighted pull-ups, OAP · Abrahangs AM',
			load: 'MOD',
			color: 'var(--violet)',
			ex: ['pull', 'slopdens', 'abra', 'antag'],
		},
		{
			k: 'Fri',
			label: 'Fri',
			type: 'Max / Tissue',
			prime: 'Max hangs (maintenance) + Density',
			sec: 'Tissue investment, MTJ density',
			load: 'MOD',
			color: 'var(--teal)',
			ex: ['maxhang', 'density'],
		},
		{
			k: 'Sat',
			label: 'Sat',
			type: 'Performance',
			prime: 'Outdoor / Performance',
			sec: 'Hangboard = warm-up only',
			load: 'HIGH',
			color: 'var(--flag)',
			ex: ['perform'],
		},
		{
			k: 'Sun',
			label: 'Sun',
			type: 'Rest',
			prime: 'Full rest',
			sec: 'No finger loading · walk / mobility',
			load: 'OFF',
			color: 'var(--ink-faint)',
			ex: ['rest'],
		},
	],
	exercises: {
		recruit: {
			name: 'Recruitment Pulls',
			cat: 'RFD / Contact',
			variants: [
				{
					name: 'Hangboard · 1-arm ~20mm',
					what: '1-arm · ~20mm or flat edge',
					note: 'Fast, explosive max pull.',
					why: [
						"Highest-yield finger stimulus once you're already strong — trains <b>rate of force development</b> and contact strength with very little fatigue.",
						'Tyler Nelson: at high levels, force <b>application</b> matters more than more max force.',
					],
				},
				{
					name: 'Campus-board controlled max touches',
					what: 'Controlled max-reach touches',
					note: 'Precise max touches to a fixed rung — full rest, quality over sloppy campusing.',
					why: ['Same recruitment intent with a controlled catch — quality over sloppy campusing.'],
				},
				{
					name: 'Lattice-block one-arm max lifts',
					what: 'One-arm block pull · ~20mm',
					note: 'Near-max one-arm lift on a block.',
					why: ['Device-measured pulls load precisely and let you track contact force.'],
				},
				{
					name: 'Heavy first-move limit attempts',
					what: 'Hard first moves off the ground',
					note: 'Repeated max attempts at a hard first move · full rest.',
					why: ['Recruitment expressed on real holds — maximal pulls into one hard move.'],
				},
			],
		},
		limitboulder: {
			name: 'Limit Bouldering',
			cat: 'Power / Skill',
			variants: [
				{
					name: 'Hardest problems · long rests',
					what: 'Hardest problems · long rests',
					note: 'Prioritise crimp / contact moves. Quality over quantity.',
					why: [
						'Where strength becomes climbing. Quality over quantity — rest fully between attempts.',
					],
				},
				{
					name: 'Moonboard / Kilter limit problems',
					what: 'Board limit problems',
					note: 'Crimp-heavy board benchmarks.',
					why: ['Standardised holds make limit power repeatable and trackable.'],
				},
				{
					name: 'Hard 4×4-style power problems',
					what: 'Power circuits near limit',
					note: 'Short rest within, long between rounds — power-endurance edge near limit.',
					why: ['Adds a power-endurance edge while staying near limit strength.'],
				},
				{
					name: 'Outdoor boulder project session',
					what: 'Rock project',
					note: 'Full warm-up · work a true project · generous rest between goes.',
					why: ["Real rock recruits power and skill the gym can't replicate."],
				},
			],
		},
		pinch: {
			name: 'Pinch Block',
			cat: 'Pinch',
			variants: [
				{
					name: 'Max — thumb-pad-depth block',
					what: 'One thumb-pad-depth block',
					note: 'Shoulders retracted, arm by side, lift with legs · ~30s between arms.',
					why: [
						"Shoulders retracted, arm by side, lift with legs. <b>Never</b> front-facing pinch hangs — De Quervain's risk (López).",
						'Rotate block width across the 8 weeks; go narrower / pads-only in Phase 2.',
					],
				},
				{
					name: 'Two-hand pinch deadlift on bar',
					what: 'Two-hand pinch off the floor',
					note: 'Near-max two-hand pinch lift off the floor.',
					why: ['Heavier loading with two hands — great for raw pinch strength.'],
				},
				{
					name: 'Wide-pinch hangs on a 40°+ board',
					what: 'Wide pinches on a steep board',
					note: 'Hold / move on wide pinches · full rest.',
					why: ['Trains thumb opposition in a climbing-specific position.'],
				},
				{
					name: 'Rockstar / Tension pinch rail max',
					what: 'Commercial pinch rail',
					note: 'Max lifts per width; rotate widths.',
					why: ['A repeatable pinch rail makes loading and tracking easy.'],
				},
			],
		},
		wrist: {
			name: 'Wrist / Sloper Strength',
			cat: 'Wrist / Slopers',
			variants: [
				{
					name: 'Wrist-wrench / radial lifts',
					what: 'Wrist-wrench / radial lifts',
					note: 'To failure · hypertrophy dose for FCR + wrist stabilisers.',
					why: [
						'Builds FCR + wrist stabilisers for slopers and compression demand.',
						'Ferrer-Uris 2023: 60mm sloper ≈ half-crimp FDP activation, with <b>better</b> FCR/FDS and lower injury risk.',
					],
				},
				{
					name: 'Big-sloper density hangs (60mm)',
					what: '60mm sloper · open hand',
					note: '2 arms · open-hand.',
					why: ['Loads the wrist + FCR in a sloper position with low pulley cost.'],
				},
				{
					name: 'Reverse + standard wrist curls (heavy)',
					what: 'Loaded wrist curls',
					note: 'Heavy, scalable wrist hypertrophy.',
					why: ['Direct, scalable wrist hypertrophy for elbow and wrist resilience.'],
				},
				{
					name: 'Compression board / pinch-sloper system',
					what: 'Compression holds',
					note: 'Holds / moves on compression features.',
					why: ['Trains wrist stability under compression demand.'],
				},
			],
		},
		repeaters: {
			name: 'Repeaters',
			cat: 'Endurance / CF',
			variants: [
				{
					name: '7/3 · 20mm half-crimp + open hand',
					what: '20mm · half-crimp + open hand',
					note: '2 grips: half-crimp + open hand.',
					why: [
						'Builds glycolytic capacity, pump resistance, <b>critical force</b> — your likely real gap given how strong your max is.',
						'Phase 2: drop to 2–3 sets/grip @ ~65–70% to stay snappy for weekends.',
					],
				},
				{
					name: '6:10 (longer recovery)',
					what: '6s on / 10s off',
					note: 'Longer rests bias aerobic capacity over glycolytic stress.',
					why: ['Longer rests bias aerobic capacity over glycolytic stress.'],
				},
				{
					name: 'Critical-force protocol (4s/4s to failure)',
					what: '4s on / 4s off to failure',
					note: 'On/off to failure — until force settles to steady state.',
					why: ['Directly probes and builds your <b>critical force</b> floor.'],
				},
				{
					name: 'On-the-wall lap intervals / boulder 4×4',
					what: 'Wall laps / 4×4',
					note: 'Sub-limit · build a pump, stop before failure.',
					why: ['Transfers repeater capacity to real movement.'],
				},
			],
		},
		sport: {
			name: 'Sport Climbing',
			cat: 'Endurance / CF',
			variants: [
				{
					name: 'Board laps · controlled pump',
					what: 'Sub-maximal, controlled pump',
					note: 'Routes or board laps · build a pump but never to failure.',
					why: ['Translates the repeater stimulus to real movement and aerobic capacity.'],
				},
				{
					name: 'Sport routes / auto-belay laps',
					what: 'Route mileage',
					note: 'Continuous easy–moderate routes · rest as needed.',
					why: ['Aerobic base on real routes — keep the effort moderate.'],
				},
				{
					name: 'Board climbing volume (easy angle)',
					what: 'Easy-angle volume',
					note: 'Many easy board problems · ~20–30 min steady pump.',
					why: ['High-volume movement quality and capillarity.'],
				},
				{
					name: 'Circuit / ARC traversing 2×15–20 min',
					what: 'ARC traverse',
					note: '2×15–20 min continuous easy traversing (<b>ARC</b>).',
					why: ['Classic <b>ARC</b> work for endurance base and recovery.'],
				},
			],
		},
		pull: {
			name: 'Pull Strength',
			cat: 'Pull power',
			variants: [
				{
					name: 'Heavy weighted pull-ups + OAP',
					what: 'Weighted pull-ups + OAP work',
					note: 'Hard but clean · OAP negatives / assisted 3–4 sets/side.',
					why: [
						'On a low-finger-cost day on purpose — pulling power without grinding skin or pulleys.',
						'Phase 2: shift toward lower reps / higher load or more OAP skill work.',
					],
				},
				{
					name: 'One-arm pull-up skill ladder',
					what: 'OAP progressions',
					note: 'Assisted → negatives → singles · full rest.',
					why: ['Builds toward the one-arm pull with high neural demand and low finger cost.'],
				},
				{
					name: 'Frenchies / tempo weighted pulls',
					what: 'Tempo + isometric holds',
					note: 'Frenchies (pause 90° / full lock) or tempo weighted pulls.',
					why: ['Adds time-under-tension and lock-off strength.'],
				},
				{
					name: 'Front-lever + weighted pull combo',
					what: 'Front-lever + pull',
					note: 'Front-lever progressions + weighted pulls.',
					why: ['Core-driven pulling power for steep terrain.'],
				},
			],
		},
		slopdens: {
			name: 'Sloper Density',
			cat: 'Tissue',
			variants: [
				{
					name: 'Sloper bottom-edge hangs',
					what: 'Bottom edge of a sloper',
					note: '2 arms · open-hand position.',
					why: ["Open-hand tissue work that doesn't tax pulleys — pairs well after the pull day."],
				},
				{
					name: 'Open-hand 35mm density hangs',
					what: '35mm · open hand',
					note: '2 arms · open hand · near-sub-max.',
					why: ['Open-hand tissue load on a defined edge.'],
				},
				{
					name: 'Big-rung repeaters (open hand)',
					what: 'Big rung · open hand',
					note: 'Long repeaters on a big rung.',
					why: ['Tissue volume with minimal pulley stress.'],
				},
				{
					name: 'No-hang open-hand long holds',
					what: 'No-hang block · open hand',
					note: '2 arms · no-hang block.',
					why: ['Easy to load and pulley-friendly — great for tweaky days.'],
				},
			],
		},
		maxhang: {
			name: 'Max Hangs',
			cat: 'Max strength',
			variants: [
				{
					name: 'Maintenance · ~10mm',
					what: 'Short dose · ~10mm edge',
					note: 'Leave a 2–3s margin (López <b>MAW</b>/<b>MED</b>, minimal).',
					why: [
						"You're <b>maintaining</b>, not chasing PRs — your max is near ceiling and extra volume here is mostly injury cost.",
					],
				},
				{
					name: 'MED — bodyweight on smaller edge',
					what: 'Minimum edge depth · bodyweight',
					note: 'Smallest manageable edge (López <b>MED</b>).',
					why: ['López <b>MED</b>: shrink the edge instead of adding weight.'],
				},
				{
					name: 'MAW — 18–20mm + added weight',
					what: 'Max added weight · 18–20mm',
					note: '2–3s margin (López <b>MAW</b>).',
					why: ['López <b>MAW</b>: add weight on a friendlier edge.'],
				},
				{
					name: 'No-hang max block lifts (10s)',
					what: 'No-hang block max',
					note: 'Near-max block lifts.',
					why: ['Pulley-friendly max strength you can load precisely.'],
				},
			],
		},
		density: {
			name: 'Density Hangs',
			cat: 'Tissue',
			variants: [
				{
					name: 'Half-crimp · near failure',
					what: 'Near-failure long holds',
					note: 'Near failure · half-crimp.',
					why: [
						'Your main connective-tissue investment. Raises muscle + MTJ stiffness while <b>reducing</b> pathological tendon stiffness — a net more injury-resistant system (Nelson).',
					],
				},
				{
					name: 'Open hand · long holds',
					what: 'Open hand · long holds',
					note: 'Near failure · open hand.',
					why: ['Same tissue stimulus shifted to the open-hand position.'],
				},
				{
					name: 'No-hang density block lifts',
					what: 'No-hang block',
					note: 'Near failure · no-hang block.',
					why: ['Pulley-friendly density loading.'],
				},
				{
					name: 'Long-duration repeaters @ low %',
					what: 'Low-% long repeaters',
					note: 'Long on/off repeaters · several sets.',
					why: ['Accumulates tissue time-under-load with low peak force.'],
				},
			],
		},
		abra: {
			name: 'Abrahangs',
			cat: 'Tissue',
			variants: [
				{
					name: 'Hangboard · 2 hands',
					what: 'Wall hangboard · both hands · 18–22mm',
					note: '"Light strain only" · ~10 min · across grips · ≥6h from hard work.',
					tool: 'Hangboard · 2 hands',
					speed: 'Standard',
					why: [
						'Additive to max work for tissue health (Gilmore/Baar 2024). At your strength, keep these genuinely <b>light</b> — err under 40%.',
						'These are training, not rest — drop them <b>first</b> at any tweak.',
					],
				},
				{
					name: 'Block · 1 hand',
					what: 'No-hang pin/block · one hand at a time',
					note: 'One arm at a time on a loading pin · switch hands each rep · keep it light.',
					tool: 'Block · 1 hand',
					speed: 'Standard',
					why: ['Per-hand no-hang loading — precise and easy to keep well under 40%.'],
				},
				{
					name: 'Hangboard · 2 hands · fast',
					what: 'abrafast · 15s on / 20s off · 13 rounds',
					note: 'Faster abrahang: longer holds, fewer rounds.',
					tool: 'Hangboard · 2 hands',
					speed: 'Fast',
					why: ['Same light tissue stimulus, quicker to fit in.'],
				},
				{
					name: 'Block · 1 hand · fast',
					what: 'abrafast 1-handed · alternate hands each rep',
					note: 'Switch hands each rep (2s) · 2 cycles.',
					tool: 'Block · 1 hand',
					speed: 'Fast',
					why: ['Per-hand fast version — alternate hands, minimal rest.'],
				},
			],
		},
		antag: {
			name: 'Antagonists',
			cat: 'Prehab',
			variants: [
				{
					name: 'Full circuit',
					what: '~10 min · elbow + pulley insurance',
					note: 'Reverse wrist curls 3×15 · band finger extensions 3×20–30 · pronation/supination 3×12 · push-ups/dips.',
					why: ['Essential given your flexor dominance — protects elbows and pulleys.'],
				},
				{
					name: 'Rice-bucket + extensor bands',
					what: 'Rice bucket + bands',
					note: '~5–8 min · rice-bucket + band finger extensions.',
					why: ['Low-effort extensor and forearm endurance work.'],
				},
				{
					name: 'Theraband finger extensions only',
					what: 'Band extensions',
					note: 'Daily-friendly extensor balance.',
					why: ['Minimal-dose extensor balance when short on time.'],
				},
				{
					name: 'Push/pronation circuit',
					what: 'Push + pronation',
					note: '~8–10 min · push-ups / dips + pronation/supination.',
					why: ['Pushing + rotation balance for shoulders and elbows.'],
				},
			],
		},
		perform: {
			name: 'Performance',
			cat: 'Skill',
			variants: [
				{
					name: 'Outdoor send day',
					what: 'Hangboard = warm-up only',
					note: 'Your hardest real climbing of the week · full warm-up · send mindset.',
					why: ['During send windows the hangboard drops to a warm-up tool (Hörst).'],
				},
				{
					name: 'Hard gym performance day',
					what: 'Gym performance',
					note: 'Hardest gym climbing · full warm-up · real send attempts.',
					why: ["A performance stimulus when rock isn't an option."],
				},
				{
					name: 'Comp-style flash session',
					what: 'Flash session',
					note: 'Onsight / flash a spread of problems · short prep per problem.',
					why: ['Trains reading and first-go execution.'],
				},
				{
					name: 'Long multi-boulder outdoor day',
					what: 'Volume on rock',
					note: 'Many boulders across the day · manage skin and energy.',
					why: ['High-quality outdoor mileage and skill.'],
				},
			],
		},
		rest: {
			name: 'Rest',
			cat: 'Recovery',
			variants: [
				{
					name: 'Full rest',
					what: 'No finger loading',
					note: 'Walk · mobility · sleep · eat. Adaptation happens now, not on the wall.',
					why: ['Even at your level the cap is ~3 high-CNS days/week. This is non-negotiable.'],
				},
				{
					name: 'Light walk + mobility only',
					what: 'Walk + mobility',
					note: 'Easy walk + 10–15 min mobility · no grip load.',
					why: ["Active recovery that doesn't tax the fingers."],
				},
				{
					name: 'Easy aerobic (no grip)',
					what: 'Easy aerobic',
					note: '20–40 min easy cardio · no grip.',
					why: ['Promotes recovery and aerobic base without finger load.'],
				},
				{
					name: 'Gentle Abrahangs only if itching to move',
					what: 'Gentle Abrahangs',
					note: 'Very light Abrahangs only if you must.',
					why: ['The most you should do on a rest day, and only if fresh.'],
				},
			],
		},
	},
	metrics: [
		{
			id: 'rfd',
			name: 'Rate of Force Dev',
			abbr: 'RFD',
			cat: '--flag',
			unit: '%/100ms',
			desc: 'How fast you reach peak force. Test: max recruitment pull, note time-to-peak feel or device value.',
		},
		{
			id: 'contact',
			name: 'Contact Strength',
			abbr: 'CONTACT',
			cat: '--flag',
			unit: 'kg / edge',
			desc: 'Force you catch instantly on small holds. Test: heaviest 3s recruitment pull on a fixed edge.',
		},
		{
			id: 'cf',
			name: 'Critical Force',
			abbr: 'CF',
			cat: '--gold',
			unit: '% MVC',
			desc: 'Sustainable force floor — your endurance ceiling. Test: repeater protocol to failure.',
		},
		{
			id: 'pinch',
			name: 'Pinch Max',
			abbr: 'PINCH',
			cat: '--gold',
			unit: 'kg / 7s',
			desc: 'Best 7-second pinch-block lift. Test each arm.',
		},
		{
			id: 'pull',
			name: 'Weighted Pull',
			abbr: 'PULL',
			cat: '--violet',
			unit: 'kg added',
			desc: 'Top weighted chin/pull-up for a clean rep.',
		},
		{
			id: 'maxhang',
			name: 'Max Hang',
			abbr: 'MAXHANG',
			cat: '--violet',
			unit: 'kg @ 20mm',
			desc: 'Standard benchmark — max added weight, 10s, 20mm edge.',
		},
		{
			id: 'density',
			name: 'Density Hold',
			abbr: 'DENSITY',
			cat: '--teal',
			unit: 'sec @ load',
			desc: 'Longest quality density hold at working load — tissue capacity proxy.',
		},
	],
	quiz: [
		{
			id: 'recovery',
			q: 'How recovered do you feel?',
			a: [
				{ t: 'Fresh & fired up', v: 2 },
				{ t: 'Normal', v: 1 },
				{ t: 'A bit flat', v: 0 },
				{ t: 'Wrecked / sore', v: -2 },
			],
		},
		{
			id: 'fingers',
			q: 'How do your fingers feel?',
			a: [
				{ t: '100% — no niggles', v: 2 },
				{ t: 'Fine, slight stiffness', v: 1 },
				{ t: 'Tender on a knuckle/pulley', v: -2 },
				{ t: 'Sharp pain anywhere', v: -5 },
			],
		},
		{
			id: 'slot',
			q: "What's the slot today?",
			a: [
				{ t: 'Big session, lots of time', v: 2 },
				{ t: 'Standard session', v: 1 },
				{ t: 'Short — 30–45 min', v: 0 },
				{ t: 'Almost no time', v: -1 },
			],
		},
		{
			id: 'skin',
			q: 'How is your skin?',
			a: [
				{ t: 'Solid — no splits', v: 1 },
				{ t: 'Okay', v: 0 },
				{ t: 'Thin / worn', v: -1 },
				{ t: 'Split or raw', v: -2 },
			],
		},
		{
			id: 'cns',
			q: 'Energy & drive?',
			a: [
				{ t: 'Sharp & motivated', v: 1 },
				{ t: 'Normal', v: 0 },
				{ t: 'Flat', v: -1 },
				{ t: 'Drained', v: -2 },
			],
		},
	],
	verdicts: {
		rest: {
			title: 'Stop — rest the fingers',
			tag: 'Pain protocol',
			color: 'var(--flag)',
			text: 'Sharp finger pain is a hard stop. <b>No loading today.</b> Pulley injuries are ~60% of finger injuries and driven by pushing through exactly this. If it persists past 3–5 days, get it assessed. Today: gentle mobility, sleep, food.',
			focus: ['REST', 'assess', 'no hangboard'],
		},
		tissue: {
			title: 'Tissue / recovery day',
			tag: 'Low load only',
			color: 'var(--teal)',
			text: "You're under-recovered or carrying a niggle. Run <b>low-load tissue work only</b>: light Abrahangs (well under 40%), antagonists, easy mobility. This is productive — connective tissue is your bottleneck anyway — and it protects the hard days.",
			focus: ['Abrahangs', 'antagonists', 'wrist mobility'],
		},
		moderate: {
			title: 'Moderate — endurance or grip-type',
			tag: 'Quality, not max',
			color: 'var(--gold)',
			text: 'Good enough to train, not to go to your limit. Best picks: <b>7/3 repeaters</b> for critical force, or a <b>pinch / wrist / sloper</b> session. Avoid maximal recruitment and limit bouldering today — save the CNS.',
			focus: ['repeaters', 'pinch', 'sloper', 'critical force'],
		},
		short: {
			title: 'Short & sharp — contact strength',
			tag: 'High value, low volume',
			color: 'var(--flag)',
			text: "You're fresh but short on time. Perfect for <b>recruitment pulls</b> — 2–3 sets trains RFD and contact strength in ~15 min with minimal fatigue. Warm up properly first; quality over quantity.",
			focus: ['recruitment pulls', 'RFD', 'contact strength'],
		},
		green: {
			title: 'Green light — go hard',
			tag: 'Limit / max day',
			color: 'var(--flag)',
			text: 'Fresh, fingers good, time and skin to spend. Run a <b>hard day</b>: recruitment pulls into <b>limit bouldering</b>, or a heavy pull day. Take full rests between maximal efforts. Fuel collagen ~60 min before: 15g collagen + 50mg vit C.',
			focus: ['recruitment pulls', 'limit bouldering', 'heavy pull'],
		},
	},
	phases: {
		phase1: {
			name: 'Phase 1 · Capacity & Tissue Base (Wk 1–4)',
			banner:
				'Build recruitment quality, establish pinch 7s max, higher repeater volume, build pull volume + OAP negatives, full density. Collagen + vit C ~60 min before heaviest finger session.',
			cat: '--gold',
		},
		phase2: {
			name: 'Phase 2 · Expression & Peaking (Wk 5–7)',
			banner:
				'Emphasise contact strength on worse holds; narrower pinch; cut repeater sets to stay powerful; pull shifts to lower-rep/higher-load. Max hangs stay minimal.',
			cat: '--flag',
		},
		deload: {
			name: 'Week 8 · Deload',
			banner:
				"Halve volume AND intensity. Two short hangboard sessions, big margins. Easy climbing only. KEEP light Abrahangs — true unloading costs ~10–20% tendon collagen in days (Baar). Adaptations surface now as fatigue clears. Retest at week's end.",
			cat: '--teal',
		},
	},
	glossary: {
		CNS: 'Central nervous system — the systemic fatigue that caps maximal, high-intensity efforts.',
		RFD: 'Rate of force development — how fast you reach peak force, not just how much.',
		MVC: 'Maximal voluntary contraction — your maximum force on a given grip.',
		MTJ: 'Muscle–tendon junction — where muscle transitions into tendon.',
		OAP: 'One-arm pull-up.',
		FCR: 'Flexor carpi radialis — a wrist flexor on the thumb side.',
		FDP: 'Flexor digitorum profundus — the deep finger flexor that drives crimping.',
		FDS: 'Flexor digitorum superficialis — a superficial finger flexor.',
		CF: 'Critical force — the highest force you can sustain almost indefinitely; your endurance floor.',
		MAW: 'Max Added Weight — a López hangboard protocol: fixed edge, add weight.',
		MED: 'Minimum Edge Depth — a López protocol: bodyweight on a progressively smaller edge.',
		ARC: 'Aerobic Restoration & Capillarity — easy continuous climbing to build an endurance base.',
		"De Quervain's": "De Quervain's tenosynovitis — irritation of the thumb-side wrist tendons.",
	},
};

export default content;
