// Language-neutral exercise parameters: target ranges (canonical units —
// counts, seconds, kg, mm, %, RPE 0–10) and metadata (grip, qualities, region,
// CNS cost, tracked metrics). Localized prose lives in the per-locale files and
// is merged with this by `getContent()`, matched by exercise id + variant index.
//
// Timer semantics: `rounds` = work/rest cycles WITHIN one set (separated by
// `restSec`); `sets` = number of sets (separated by `setRestSec`). Single-effort
// work (hangs, lifts) leaves `rounds` unset (= 1 rep per set).
import type { ExerciseParams, Range } from './types';

/** Build a range; a single argument means a fixed value (min === max). */
const n = (min: number, max: number = min): Range => ({ min, max });

export const exerciseParams: Record<string, ExerciseParams> = {
	recruit: {
		catVar: '--flag',
		variants: [
			{
				workSec: n(3, 5),
				restSec: n(5),
				rounds: n(4),
				reps: n(4),
				sets: n(2, 3),
				edgeMm: n(20),
				rpe: n(8, 9),
				grip: 'half-crimp',
				qualities: ['rfd', 'max-strength'],
				region: ['fingers'],
				cnsCost: 'high',
				metricIds: ['rfd', 'contact'],
			},
			{
				reps: n(4, 6),
				sets: n(3, 4),
				rpe: n(8, 9),
				grip: 'half-crimp',
				qualities: ['rfd', 'power'],
				region: ['fingers'],
				cnsCost: 'high',
				metricIds: ['rfd', 'contact'],
			},
			{
				workSec: n(3, 5),
				restSec: n(5),
				rounds: n(4),
				reps: n(4),
				sets: n(2, 3),
				edgeMm: n(20),
				rpe: n(8, 9),
				grip: 'half-crimp',
				qualities: ['rfd', 'max-strength'],
				region: ['fingers'],
				cnsCost: 'high',
				metricIds: ['rfd', 'contact'],
			},
			{
				reps: n(6, 10),
				rpe: n(9, 10),
				grip: 'half-crimp',
				qualities: ['rfd', 'power', 'skill'],
				region: ['fingers'],
				cnsCost: 'high',
				metricIds: ['rfd', 'contact'],
			},
		],
	},
	limitboulder: {
		catVar: '--flag',
		variants: [
			{
				sets: n(4, 6),
				setRestSec: n(180, 300),
				rpe: n(9, 10),
				grip: 'half-crimp',
				qualities: ['power', 'skill', 'max-strength'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				sets: n(4, 6),
				setRestSec: n(180, 300),
				rpe: n(9, 10),
				grip: 'half-crimp',
				qualities: ['power', 'skill'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				sets: n(4),
				rounds: n(4),
				setRestSec: n(180),
				rpe: n(8, 9),
				grip: 'half-crimp',
				qualities: ['power', 'strength-endurance'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				setRestSec: n(180, 300),
				rpe: n(9, 10),
				qualities: ['power', 'skill'],
				region: ['fingers'],
				cnsCost: 'high',
			},
		],
	},
	pinch: {
		catVar: '--gold',
		variants: [
			{
				workSec: n(7, 10),
				setRestSec: n(180),
				sets: n(5, 7),
				intensityPct: n(90),
				rpe: n(8, 9),
				grip: 'pinch',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['pinch'],
			},
			{
				workSec: n(5, 7),
				setRestSec: n(180),
				sets: n(4, 5),
				rpe: n(8, 9),
				grip: 'pinch',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['pinch'],
			},
			{
				sets: n(4, 6),
				rpe: n(7, 8),
				grip: 'pinch',
				qualities: ['max-strength', 'power'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['pinch'],
			},
			{
				workSec: n(7, 10),
				setRestSec: n(120),
				sets: n(4, 5),
				rpe: n(8, 9),
				grip: 'pinch',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['pinch'],
			},
		],
	},
	wrist: {
		catVar: '--gold',
		variants: [
			{
				workSec: n(20, 40),
				setRestSec: n(120),
				sets: n(3, 5),
				intensityPct: n(65, 75),
				rpe: n(9, 10),
				toFailure: true,
				grip: 'wrist',
				qualities: ['hypertrophy'],
				region: ['wrist'],
				cnsCost: 'mod',
			},
			{
				workSec: n(30, 45),
				setRestSec: n(120),
				sets: n(3, 4),
				edgeMm: n(60),
				rpe: n(7, 8),
				grip: 'sloper',
				qualities: ['tissue', 'hypertrophy'],
				region: ['wrist', 'fingers'],
				cnsCost: 'low',
			},
			{
				reps: n(10, 15),
				sets: n(3, 4),
				setRestSec: n(120),
				rpe: n(8, 9),
				grip: 'wrist',
				qualities: ['hypertrophy'],
				region: ['wrist'],
				cnsCost: 'low',
			},
			{
				sets: n(4, 6),
				rpe: n(7, 8),
				grip: 'sloper',
				qualities: ['hypertrophy', 'skill'],
				region: ['wrist'],
				cnsCost: 'mod',
			},
		],
	},
	repeaters: {
		catVar: '--gold',
		variants: [
			{
				workSec: n(7),
				restSec: n(3),
				rounds: n(6),
				setRestSec: n(180),
				sets: n(3, 4),
				edgeMm: n(20),
				intensityPct: n(60),
				rpe: n(7, 9),
				grip: 'half-crimp',
				qualities: ['strength-endurance'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['cf'],
			},
			{
				workSec: n(6),
				restSec: n(10),
				rounds: n(6),
				setRestSec: n(180),
				sets: n(3, 4),
				intensityPct: n(60),
				rpe: n(6, 8),
				grip: 'half-crimp',
				qualities: ['aerobic', 'strength-endurance'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['cf'],
			},
			{
				workSec: n(4),
				restSec: n(4),
				setRestSec: n(180),
				sets: n(2, 3),
				rpe: n(9, 10),
				toFailure: true,
				grip: 'half-crimp',
				qualities: ['strength-endurance'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['cf'],
			},
			{
				sets: n(4),
				rounds: n(4),
				rpe: n(7, 8),
				grip: 'open-hand',
				qualities: ['strength-endurance', 'skill'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['cf'],
			},
		],
	},
	sport: {
		catVar: '--gold',
		variants: [
			{
				rpe: n(5, 7),
				grip: 'open-hand',
				qualities: ['aerobic', 'strength-endurance', 'skill'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			{
				sets: n(4, 8),
				rpe: n(4, 6),
				qualities: ['aerobic', 'skill'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			{
				rpe: n(4, 6),
				qualities: ['aerobic', 'skill'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			{
				rpe: n(3, 5),
				qualities: ['aerobic'],
				region: ['fingers'],
				cnsCost: 'low',
			},
		],
	},
	pull: {
		catVar: '--violet',
		variants: [
			{
				sets: n(4, 6),
				reps: n(3, 5),
				loadKg: n(30, 45),
				setRestSec: n(180),
				rpe: n(8, 9),
				grip: 'jug',
				qualities: ['max-strength', 'power'],
				region: ['pull'],
				cnsCost: 'mod',
				metricIds: ['pull'],
			},
			{
				sets: n(4, 5),
				setRestSec: n(180),
				rpe: n(8, 9),
				grip: 'jug',
				qualities: ['max-strength', 'skill'],
				region: ['pull'],
				cnsCost: 'mod',
				metricIds: ['pull'],
			},
			{
				sets: n(3, 4),
				rpe: n(7, 9),
				grip: 'jug',
				qualities: ['max-strength', 'strength-endurance'],
				region: ['pull'],
				cnsCost: 'mod',
				metricIds: ['pull'],
			},
			{
				sets: n(3, 4),
				rpe: n(8, 9),
				grip: 'jug',
				qualities: ['max-strength', 'power'],
				region: ['pull'],
				cnsCost: 'mod',
				metricIds: ['pull'],
			},
		],
	},
	slopdens: {
		catVar: '--teal',
		variants: [
			{
				workSec: n(30, 45),
				setRestSec: n(120),
				sets: n(3),
				rpe: n(6, 8),
				grip: 'sloper',
				qualities: ['tissue'],
				region: ['fingers', 'wrist'],
				cnsCost: 'low',
			},
			{
				workSec: n(30, 45),
				setRestSec: n(120),
				sets: n(3),
				edgeMm: n(35),
				rpe: n(6, 8),
				grip: 'open-hand',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			{
				sets: n(3),
				intensityPct: n(50),
				rpe: n(5, 7),
				grip: 'open-hand',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			{
				workSec: n(30, 45),
				setRestSec: n(120),
				sets: n(3),
				rpe: n(6, 8),
				grip: 'open-hand',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
		],
	},
	maxhang: {
		catVar: '--violet',
		variants: [
			{
				workSec: n(10),
				setRestSec: n(180),
				sets: n(3),
				edgeMm: n(10),
				rpe: n(7, 8),
				grip: 'half-crimp',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['maxhang'],
			},
			{
				workSec: n(10),
				setRestSec: n(180),
				sets: n(3),
				rpe: n(7, 8),
				grip: 'half-crimp',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['maxhang'],
			},
			{
				workSec: n(10),
				setRestSec: n(180),
				sets: n(3),
				edgeMm: n(18, 20),
				rpe: n(7, 8),
				grip: 'half-crimp',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['maxhang'],
			},
			{
				workSec: n(10),
				setRestSec: n(180),
				sets: n(3),
				rpe: n(7, 8),
				grip: 'half-crimp',
				qualities: ['max-strength'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['maxhang'],
			},
		],
	},
	density: {
		catVar: '--teal',
		variants: [
			{
				workSec: n(20, 40),
				setRestSec: n(180),
				sets: n(5, 6),
				intensityPct: n(70, 75),
				rpe: n(8, 9),
				toFailure: true,
				grip: 'half-crimp',
				qualities: ['tissue', 'hypertrophy'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['density'],
			},
			{
				workSec: n(20, 40),
				setRestSec: n(180),
				sets: n(5, 6),
				rpe: n(8, 9),
				toFailure: true,
				grip: 'open-hand',
				qualities: ['tissue', 'hypertrophy'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['density'],
			},
			{
				workSec: n(20, 40),
				setRestSec: n(180),
				sets: n(5, 6),
				rpe: n(8, 9),
				toFailure: true,
				grip: 'half-crimp',
				qualities: ['tissue', 'hypertrophy'],
				region: ['fingers'],
				cnsCost: 'mod',
				metricIds: ['density'],
			},
			{
				intensityPct: n(50, 60),
				rpe: n(6, 7),
				grip: 'open-hand',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
				metricIds: ['density'],
			},
		],
	},
	abra: {
		catVar: '--teal',
		variants: [
			// Hangboard · 2 hands · Standard
			{
				prepareSec: 5,
				workSec: n(10),
				restSec: n(20),
				rounds: n(20),
				sets: n(1),
				edgeMm: n(18, 22),
				intensityPct: n(40),
				rpe: n(3, 4),
				grip: 'half-crimp',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			// Block · 1 hand · Standard (2s switch between hands, 2 cycles)
			{
				prepareSec: 5,
				workSec: n(10),
				restSec: n(2),
				rounds: n(20),
				sets: n(2),
				setRestSec: n(2),
				intensityPct: n(40),
				rpe: n(3, 4),
				grip: 'half-crimp',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			// Hangboard · 2 hands · Fast (abrafast)
			{
				prepareSec: 5,
				workSec: n(15),
				restSec: n(20),
				rounds: n(13),
				sets: n(1),
				edgeMm: n(18, 22),
				intensityPct: n(40),
				rpe: n(3, 4),
				grip: 'half-crimp',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
			// Block · 1 hand · Fast (abrafast 1-handed)
			{
				prepareSec: 5,
				workSec: n(15),
				restSec: n(2),
				rounds: n(13),
				sets: n(2),
				setRestSec: n(2),
				intensityPct: n(40),
				rpe: n(3, 4),
				grip: 'half-crimp',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
		],
	},
	antag: {
		catVar: '--teal',
		variants: [
			{
				rpe: n(5, 7),
				qualities: ['hypertrophy'],
				region: ['antagonist'],
				cnsCost: 'low',
			},
			{
				reps: n(20, 30),
				rpe: n(4, 6),
				qualities: ['hypertrophy', 'aerobic'],
				region: ['antagonist'],
				cnsCost: 'low',
			},
			{
				reps: n(20, 30),
				sets: n(3, 4),
				rpe: n(4, 6),
				qualities: ['hypertrophy'],
				region: ['antagonist'],
				cnsCost: 'low',
			},
			{
				reps: n(12),
				sets: n(3),
				rpe: n(5, 7),
				qualities: ['hypertrophy'],
				region: ['antagonist'],
				cnsCost: 'low',
			},
		],
	},
	perform: {
		catVar: '--flag',
		variants: [
			{
				rpe: n(9, 10),
				qualities: ['skill', 'power'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				rpe: n(9, 10),
				qualities: ['skill', 'power'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				rpe: n(8, 9),
				qualities: ['skill'],
				region: ['fingers'],
				cnsCost: 'high',
			},
			{
				rpe: n(7, 9),
				qualities: ['skill', 'strength-endurance'],
				region: ['fingers'],
				cnsCost: 'high',
			},
		],
	},
	rest: {
		catVar: '--ink-faint',
		variants: [
			{ cnsCost: 'low' },
			{ cnsCost: 'low' },
			{
				rpe: n(3, 4),
				qualities: ['aerobic'],
				cnsCost: 'low',
			},
			{
				intensityPct: n(40),
				rpe: n(2, 3),
				grip: 'half-crimp',
				qualities: ['tissue'],
				region: ['fingers'],
				cnsCost: 'low',
			},
		],
	},
};
