import type { Content } from './types';

const content: Content = {
	days: [
		{
			k: 'Mon',
			label: 'Seg',
			type: 'Limite / Potência',
			prime: 'Recruitment pulls → Boulder no limite',
			sec: 'Força de contato e RFD, depois os boulders mais duros',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['recruit', 'limitboulder'],
		},
		{
			k: 'Tue',
			label: 'Ter',
			type: 'Pinça / Punho',
			prime: 'Pinch block + Punho / Sloper',
			sec: 'Abrahangs de manhã · antagonistas',
			load: 'MOD',
			color: 'var(--gold)',
			ex: ['pinch', 'wrist', 'abra', 'antag'],
		},
		{
			k: 'Wed',
			label: 'Qua',
			type: 'Resistência',
			prime: 'Repeaters 7/3 → Escalada esportiva',
			sec: 'Resistência de força, força crítica, pump',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['repeaters', 'sport'],
		},
		{
			k: 'Thu',
			label: 'Qui',
			type: 'Tração',
			prime: 'Dia de tração pesada + Densidade em sloper',
			sec: 'Barras com peso, OAP · Abrahangs de manhã',
			load: 'MOD',
			color: 'var(--violet)',
			ex: ['pull', 'slopdens', 'abra', 'antag'],
		},
		{
			k: 'Fri',
			label: 'Sex',
			type: 'Máx / Tecido',
			prime: 'Max hangs (manutenção) + Densidade',
			sec: 'Investir no tecido, densidade da JMT',
			load: 'MOD',
			color: 'var(--teal)',
			ex: ['maxhang', 'density'],
		},
		{
			k: 'Sat',
			label: 'Sáb',
			type: 'Performance',
			prime: 'Rocha / Performance',
			sec: 'Hangboard = só aquecimento',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['perform'],
		},
		{
			k: 'Sun',
			label: 'Dom',
			type: 'Descanso',
			prime: 'Descanso total',
			sec: 'Sem carga nos dedos · caminhada / mobilidade',
			load: 'FOLGA',
			color: 'var(--ink-faint)',
			ex: ['rest'],
		},
	],
	exercises: {
		recruit: {
			name: 'Recruitment Pulls',
			cat: 'RFD / Contato',
			catVar: '--flag',
			what: '1 braço · régua ~20mm ou reta',
			spec: '3–5s puxando no MÁXIMO, gerando força rápido · 5s descanso · 4 reps/lado · 2–3 séries',
			why: [
				'O estímulo de dedo de maior retorno pra quem já é forte — treina a <b>taxa de desenvolvimento de força</b> e a força de contato com pouquíssima fadiga.',
				'Tyler Nelson: em nível alto, vale mais a <b>aplicação</b> da força do que mais força máxima.',
			],
			swaps: [
				'Recruitment pulls (1 braço, régua reta)',
				'Toques máximos controlados no campus',
				'Levantamento máximo de 1 braço no Lattice-block',
				'Tentativas do primeiro movimento no limite, fora da via',
			],
		},
		limitboulder: {
			name: 'Boulder no Limite',
			cat: 'Potência / Técnica',
			catVar: '--flag',
			what: 'Os boulders mais duros · descansos longos',
			spec: '4–6 boulders duros · 3–5 min de descanso · priorize movimentos de crimpa / contato',
			why: [
				'Onde a força vira escalada. Qualidade acima de quantidade — descanse por completo entre as tentativas.',
			],
			swaps: [
				'Boulder no limite (ginásio/rocha)',
				'Problemas no limite no Moonboard / Kilter',
				'Boulders de potência tipo 4×4 duros',
				'Sessão de projeto de boulder na rocha',
			],
		},
		pinch: {
			name: 'Pinch Block — Máximo',
			cat: 'Pinça',
			catVar: '--gold',
			what: 'Bloco com profundidade de uma falange',
			spec: 'Levantamentos de 7–10s · ~90% do máx de 7s · 5–7 séries · 3 min entre séries · 30s entre braços',
			why: [
				'Ombros encaixados, braço junto ao corpo, levante com as pernas. <b>Nunca</b> faça pinch hang de frente — risco de De Quervain (López).',
				'Varie a largura do bloco ao longo das 8 semanas; vá mais estreito / só na polpa na Fase 2.',
			],
			swaps: [
				'Levantar pinch block com peso',
				'Terra de pinça com as duas mãos na barra',
				'Pinch hangs largos numa board 40°+',
				'Máximo no trilho de pinça Rockstar / Tension',
			],
		},
		wrist: {
			name: 'Força de Punho / Sloper',
			cat: 'Punho',
			catVar: '--gold',
			what: 'Wrist-wrench / levantamentos radiais',
			spec: 'Hipertrofia: 20–40s até a falha @ 65–75% máx · 3–5 séries · 2 min descanso',
			why: [
				'Desenvolve o FRC e os estabilizadores do punho pra slopers e compressão.',
				'Ferrer-Uris 2023: sloper de 60mm ≈ ativação do FPD em half-crimp, com <b>melhor</b> FRC/FDS e menos risco de lesão.',
			],
			swaps: [
				'Desvio radial (wrist-wrench)',
				'Density hangs em sloper grande (60mm)',
				'Flexão de punho reversa + normal (pesadas)',
				'Board de compressão / sistema pinça-sloper',
			],
		},
		repeaters: {
			name: 'Repeaters 7/3',
			cat: 'Resistência / FC',
			catVar: '--gold',
			what: '20mm · half-crimp + mão aberta',
			spec: '~60% MVC · 7s on / 3s off ×6 = 1 série · 3–4 séries/pegada · 2 pegadas · 3 min descanso',
			why: [
				'Desenvolve capacidade glicolítica, resistência ao pump e <b>força crítica</b> — provavelmente sua lacuna real, já que seu máximo é alto.',
				'Fase 2: caia pra 2–3 séries/pegada @ ~65–70% pra chegar explosivo no fim de semana.',
			],
			swaps: [
				'Repeaters 7/3 (hangboard)',
				'Repeaters 6:10 (recuperação maior)',
				'Protocolo de força crítica (4s/4s até a falha)',
				'Voltas/laps na parede · boulder 4×4',
			],
		},
		sport: {
			name: 'Escalada Esportiva / Voltas na Board',
			cat: 'Resistência / FC',
			catVar: '--gold',
			what: 'Submáximo, pump controlado',
			spec: 'Vias ou voltas na board · faça pump, mas nunca até a falha',
			why: ['Transfere o estímulo dos repeaters pro movimento real e pra capacidade aeróbica.'],
			swaps: [
				'Vias / voltas no auto-belay',
				'Volume na board (ângulo fácil)',
				'Circuito / travessia ARC 2×15–20 min',
				'Boulders encadeados (4×4)',
			],
		},
		pull: {
			name: 'Dia de Tração Pesada',
			cat: 'Potência de tração',
			catVar: '--violet',
			what: 'Barras com peso + trabalho de OAP',
			spec: 'Com peso: 4–6 séries ×3–5 reps, duro mas limpo (~+30–45kg) · OAP: negativas / assistidas, 3–4 séries/lado',
			why: [
				'De propósito num dia de baixo custo pros dedos — potência de tração sem gastar pele nem polias.',
				'Fase 2: vá pra menos reps / mais carga, ou mais trabalho técnico de OAP.',
			],
			swaps: [
				'Barras com peso + negativas de OAP',
				'Escada de barra de 1 braço (técnica)',
				'Frenchies / barras com peso em tempo controlado',
				'Combo front-lever + barra com peso',
			],
		},
		slopdens: {
			name: 'Density Hangs em Sloper',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'Parte de baixo de um sloper',
			spec: '30–45s · 3 séries · 2 braços · mão aberta',
			why: [
				'Trabalho de tecido em mão aberta que não castiga as polias — encaixa bem depois do dia de tração.',
			],
			swaps: [
				'Density hangs em sloper',
				'Density hangs de mão aberta em 35mm',
				'Repeaters em régua grande (mão aberta)',
				'Sustentações longas de mão aberta no no-hang',
			],
		},
		maxhang: {
			name: 'Max Hangs — Manutenção',
			cat: 'Força máxima',
			catVar: '--violet',
			what: 'Dose curta · régua de ~10mm',
			spec: '3 séries ×10s · deixe 2–3s de margem · 3 min descanso (López MAW/MED, mínimo)',
			why: [
				'Aqui é <b>manutenção</b>, não recorde — seu máximo está perto do teto e volume extra vira mais custo de lesão do que ganho.',
			],
			swaps: [
				'Max hangs 10s (10mm, com margem)',
				'MED — peso corporal em régua menor',
				'MAW — 18–20mm + peso',
				'Levantamento máximo no no-hang block (10s)',
			],
		},
		density: {
			name: 'Density Hangs',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'Sustentações longas perto da falha',
			spec: '20–40s perto da falha @ ~70–75% MVC · 5–6 séries · 3 min descanso',
			why: [
				'Seu principal investimento em tecido conjuntivo. Aumenta a rigidez do músculo e da JMT e <b>reduz</b> a rigidez tendínea patológica — no saldo, um sistema mais resistente a lesão (Nelson).',
			],
			swaps: [
				'Density hangs (half-crimp)',
				'Density hangs (mão aberta)',
				'Levantamento de densidade no no-hang block',
				'Repeaters longos @ % baixo',
			],
		},
		abra: {
			name: 'Abrahangs (carga baixa)',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'De manhã · 18–22mm · pés no chão',
			spec: '~40% máx ("só tensão leve") · ~10 min no total · ~20×10s entre pegadas · ≥6h do trabalho pesado',
			why: [
				'Complementa o trabalho máximo pela saúde do tecido (Gilmore/Baar 2024). Na sua força, mantenha bem <b>leves</b> — erre pra baixo de 40%.',
				'Isto é treino, não descanso — corte <b>estes</b> primeiro a qualquer incômodo.',
			],
			swaps: [
				'Abrahangs (no-hang, pés no chão)',
				'Sustentações leves no no-hang block',
				'Repeaters longos de % baixo',
				'Pule — descanso extra se estiver cansado',
			],
		},
		antag: {
			name: 'Antagonistas',
			cat: 'Prevenção',
			catVar: '--teal',
			what: '~10 min · seguro pro cotovelo + polias',
			spec: 'Flexão de punho reversa 3×15 · extensão de dedo com elástico 3×20–30 · pronação/supinação 3×12 · flexões/dips',
			why: ['Essencial pela sua dominância flexora — protege cotovelos e polias.'],
			swaps: [
				'Antagonistas com elástico + halter',
				'Balde de arroz + elásticos extensores',
				'Só extensão de dedo com Theraband',
				'Circuito de empurrar / pronação',
			],
		},
		perform: {
			name: 'Rocha / Performance',
			cat: 'Técnica',
			catVar: '--flag',
			what: 'Hangboard = só aquecimento',
			spec: 'Sua escalada real mais difícil da semana · aquecimento completo · cabeça de send',
			why: ['Em janela de send, o hangboard vira só ferramenta de aquecimento (Hörst).'],
			swaps: [
				'Sessão de projeto na rocha',
				'Dia de performance forte no ginásio',
				'Sessão flash estilo competição',
				'Dia longo de vários boulders na rocha',
			],
		},
		rest: {
			name: 'Descanso Total',
			cat: 'Recuperação',
			catVar: '--ink-faint',
			what: 'Sem carga nos dedos',
			spec: 'Caminhe · mobilidade · durma · coma. A adaptação acontece agora, não na parede.',
			why: ['Mesmo no seu nível, o teto é ~3 dias de alto SNC por semana. Inegociável.'],
			swaps: [
				'Descanso completo',
				'Só caminhada leve + mobilidade',
				'Aeróbico leve (sem pegada)',
				'Abrahangs leves só se estiver doido pra mexer',
			],
		},
	},
	metrics: [
		{
			id: 'rfd',
			name: 'Taxa de Desenv. de Força',
			abbr: 'RFD',
			cat: '--flag',
			unit: '%/100ms',
			desc: 'Quão rápido você chega ao pico de força. Teste: recruitment pull máximo; anote a sensação de tempo até o pico ou o valor do aparelho.',
		},
		{
			id: 'contact',
			name: 'Força de Contato',
			abbr: 'CONTATO',
			cat: '--flag',
			unit: 'kg / régua',
			desc: 'Força que você segura na hora em agarras pequenas. Teste: recruitment pull de 3s mais pesado numa régua fixa.',
		},
		{
			id: 'cf',
			name: 'Força Crítica',
			abbr: 'FC',
			cat: '--gold',
			unit: '% MVC',
			desc: 'Piso de força sustentável — seu teto de resistência. Teste: protocolo de repeaters até a falha.',
		},
		{
			id: 'pinch',
			name: 'Pinça Máxima',
			abbr: 'PINÇA',
			cat: '--gold',
			unit: 'kg / 7s',
			desc: 'Melhor levantamento de pinch block de 7 segundos. Teste cada braço.',
		},
		{
			id: 'pull',
			name: 'Tração com Peso',
			abbr: 'TRAÇÃO',
			cat: '--violet',
			unit: 'kg adicionais',
			desc: 'Melhor barra/chin-up com peso numa rep limpa.',
		},
		{
			id: 'maxhang',
			name: 'Max Hang',
			abbr: 'MAXHANG',
			cat: '--violet',
			unit: 'kg @ 10mm',
			desc: 'Referência de manutenção — peso adicional, 10s, régua de 10mm.',
		},
		{
			id: 'density',
			name: 'Sustentação de Densidade',
			abbr: 'DENSIDADE',
			cat: '--teal',
			unit: 'seg @ carga',
			desc: 'Maior sustentação de densidade com qualidade na carga de trabalho — proxy da capacidade do tecido.',
		},
	],
	quiz: [
		{
			id: 'recovery',
			q: 'Quão recuperado você se sente?',
			a: [
				{ t: 'Inteiro e ligado', v: 2 },
				{ t: 'Normal', v: 1 },
				{ t: 'Meio apagado', v: 0 },
				{ t: 'Detonado / dolorido', v: -2 },
			],
		},
		{
			id: 'fingers',
			q: 'Como estão os dedos?',
			a: [
				{ t: '100% — sem incômodo', v: 2 },
				{ t: 'Ok, leve rigidez', v: 1 },
				{ t: 'Sensível numa articulação/polia', v: -2 },
				{ t: 'Dor aguda em algum ponto', v: -5 },
			],
		},
		{
			id: 'slot',
			q: 'Quanto tempo você tem hoje?',
			a: [
				{ t: 'Sessão grande, tempo de sobra', v: 2 },
				{ t: 'Sessão normal', v: 1 },
				{ t: 'Curta — 30–45 min', v: 0 },
				{ t: 'Quase nada', v: -1 },
			],
		},
		{
			id: 'skin',
			q: 'Pele e SNC / disposição?',
			a: [
				{ t: 'Pele boa, me sentindo afiado', v: 2 },
				{ t: 'Ok', v: 1 },
				{ t: 'Pele fina / pouca disposição', v: -1 },
				{ t: 'Os dois no chão', v: -2 },
			],
		},
	],
	verdicts: {
		rest: {
			title: 'Pare — descanse os dedos',
			tag: 'Protocolo de dor',
			color: 'var(--flag)',
			text: 'Dor aguda no dedo é parada obrigatória. <b>Nada de carga hoje.</b> Lesão de polia é ~60% das lesões de dedo e vem justamente de forçar nessas horas. Se passar de 3–5 dias, procure um profissional. Hoje: mobilidade leve, sono e comida.',
			focus: ['DESCANSO', 'avaliar', 'sem hangboard'],
		},
		tissue: {
			title: 'Dia de tecido / recuperação',
			tag: 'Só carga baixa',
			color: 'var(--teal)',
			text: 'Você está mal recuperado ou com um incômodo. Faça <b>só trabalho de tecido em carga baixa</b>: Abrahangs leves (bem abaixo de 40%), antagonistas e mobilidade tranquila. É produtivo — o tecido é seu gargalo de qualquer jeito — e ainda protege os dias duros.',
			focus: ['Abrahangs', 'antagonistas', 'mobilidade de punho'],
		},
		moderate: {
			title: 'Moderado — resistência ou tipo de pegada',
			tag: 'Qualidade, não máximo',
			color: 'var(--gold)',
			text: 'Dá pra treinar, mas não pra ir ao limite. Melhores escolhas: <b>repeaters 7/3</b> pra força crítica, ou uma sessão de <b>pinça / punho / sloper</b>. Evite recruitment máximo e boulder no limite hoje — poupe o SNC.',
			focus: ['repeaters', 'pinça', 'sloper', 'força crítica'],
		},
		short: {
			title: 'Curto e afiado — força de contato',
			tag: 'Muito valor, pouco volume',
			color: 'var(--flag)',
			text: 'Você está inteiro mas com pouco tempo. Perfeito pra <b>recruitment pulls</b> — 2–3 séries treinam RFD e força de contato em ~15 min com fadiga mínima. Aqueça direito antes; qualidade acima de quantidade.',
			focus: ['recruitment pulls', 'RFD', 'força de contato'],
		},
		green: {
			title: 'Sinal verde — vá com tudo',
			tag: 'Dia de limite / máximo',
			color: 'var(--flag)',
			text: 'Inteiro, dedos bons, tempo e pele de sobra. Manda um <b>dia duro</b>: recruitment pulls emendando em <b>boulder no limite</b>, ou um dia de tração pesada. Descanse de verdade entre os esforços máximos. Tome colágeno ~60 min antes: 15g de colágeno + 50mg de vit. C.',
			focus: ['recruitment pulls', 'boulder no limite', 'tração pesada'],
		},
	},
	phases: {
		phase1: {
			name: 'Fase 1 · Capacidade & Base de Tecido (Sem 1–4)',
			banner:
				'Construa qualidade de recruitment, fixe o máximo de pinça de 7s, suba o volume de repeaters, ganhe volume de tração + negativas de OAP, densidade completa. Colágeno + vit. C ~60 min antes da sessão de dedo mais pesada.',
			cat: '--gold',
		},
		phase2: {
			name: 'Fase 2 · Expressão & Pico (Sem 5–7)',
			banner:
				'Enfatize força de contato em agarras piores; pinça mais estreita; corte séries de repeaters pra manter a potência; tração vai pra menos reps / mais carga. Max hangs seguem no mínimo.',
			cat: '--flag',
		},
		deload: {
			name: 'Semana 8 · Deload',
			banner:
				'Corte volume E intensidade pela metade. Duas sessões curtas de hangboard, com bastante margem. Só escalada leve. MANTENHA os Abrahangs leves — descarregar de verdade custa ~10–20% do colágeno do tendão em poucos dias (Baar). As adaptações aparecem agora, conforme a fadiga passa. Reteste no fim da semana.',
			cat: '--teal',
		},
	},
	glossary: {
		SNC: 'Sistema nervoso central — a fadiga sistêmica que limita os esforços máximos e intensos.',
		RFD: 'Taxa de desenvolvimento de força — quão rápido você chega ao pico de força.',
		MVC: 'Contração voluntária máxima — sua força máxima numa dada pegada.',
		JMT: 'Junção miotendínea — onde o músculo vira tendão.',
		OAP: 'Barra de um braço (one-arm pull-up).',
		FRC: 'Flexor radial do carpo — um flexor do punho, do lado do polegar.',
		FPD: 'Flexor profundo dos dedos — o flexor profundo que comanda a crimpa.',
		FDS: 'Flexor superficial dos dedos.',
		FC: 'Força crítica — a maior força que você sustenta quase indefinidamente; seu piso de resistência.',
		MAW: 'Max Added Weight — protocolo de hangboard da López: régua fixa, adicionando peso.',
		MED: 'Minimum Edge Depth — protocolo da López: peso corporal em régua cada vez menor.',
		ARC: 'Aerobic Restoration & Capillarity — escalada contínua e fácil pra base de resistência.',
		'De Quervain':
			'Tenossinovite de De Quervain — irritação dos tendões do punho, do lado do polegar.',
	},
};

export default content;
