import type { Content } from './types';

const content: Content = {
	days: [
		{
			k: 'Mon',
			label: 'Seg',
			prime: 'Recruitment pulls → Boulder no limite',
			sec: 'Força de contato / RFD, depois os problemas mais difíceis',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['recruit', 'limitboulder'],
		},
		{
			k: 'Tue',
			label: 'Ter',
			prime: 'Pinch block + Punho / Sloper',
			sec: 'Abrahangs de manhã · antagonistas',
			load: 'MOD',
			color: 'var(--gold)',
			ex: ['pinch', 'wrist', 'abra', 'antag'],
		},
		{
			k: 'Wed',
			label: 'Qua',
			prime: 'Repeaters 7/3 → Escalada esportiva',
			sec: 'Resistência de força, força crítica, pump',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['repeaters', 'sport'],
		},
		{
			k: 'Thu',
			label: 'Qui',
			prime: 'Dia de tração pesada + Densidade em sloper',
			sec: 'Pull-ups com peso, OAP · Abrahangs de manhã',
			load: 'MOD',
			color: 'var(--violet)',
			ex: ['pull', 'slopdens', 'abra', 'antag'],
		},
		{
			k: 'Fri',
			label: 'Sex',
			prime: 'Max hangs (manutenção) + Densidade',
			sec: 'Investimento em tecido, densidade da JMT',
			load: 'MOD',
			color: 'var(--teal)',
			ex: ['maxhang', 'density'],
		},
		{
			k: 'Sat',
			label: 'Sáb',
			prime: 'Rocha / Performance',
			sec: 'Hangboard = só aquecimento',
			load: 'ALTO',
			color: 'var(--flag)',
			ex: ['perform'],
		},
		{
			k: 'Sun',
			label: 'Dom',
			prime: 'Descanso total',
			sec: 'Sem carga nos dedos · caminhada / mobilidade',
			load: 'FOLGA',
			color: 'var(--ink-faint)',
			ex: ['rest'],
		},
	],
	exercises: {
		recruit: {
			name: 'Recruitment Pulls',
			cat: 'RFD / Contato',
			catVar: '--flag',
			what: '1 braço · ~20mm ou borda reta',
			spec: '3–5s de tração MÁXIMA, geração rápida de força · 5s descanso · 4 reps/lado · 2–3 séries',
			why: [
				'O estímulo de dedo de maior retorno quando você já é forte — treina a <b>taxa de desenvolvimento de força</b> e a força de contato com pouquíssima fadiga.',
				'Tyler Nelson: em níveis altos, a <b>aplicação</b> de força importa mais do que mais força máxima.',
			],
			swaps: [
				'Recruitment pulls (1 braço, borda reta)',
				'Toques máximos controlados no campus',
				'Levantamentos máximos de 1 braço no Lattice-block',
				'Tentativas pesadas de primeiro movimento no limite, fora da parede',
			],
		},
		limitboulder: {
			name: 'Boulder no Limite',
			cat: 'Potência / Técnica',
			catVar: '--flag',
			what: 'Problemas mais difíceis · descansos longos',
			spec: '4–6 problemas difíceis · 3–5 min descanso · priorize movimentos de crimp / contato',
			why: [
				'Onde a força vira escalada. Qualidade acima de quantidade — descanse totalmente entre tentativas.',
			],
			swaps: [
				'Boulder no limite (ginásio/rocha)',
				'Problemas no limite no Moonboard / Kilter',
				'Problemas de potência tipo 4×4 difíceis',
				'Sessão de projeto de boulder na rocha',
			],
		},
		pinch: {
			name: 'Pinch Block — Máximo',
			cat: 'Pinça',
			catVar: '--gold',
			what: 'Um bloco com profundidade de uma falange',
			spec: 'Levantamentos de 7–10s · ~90% do máx de 7s · 5–7 séries · 3 min entre séries · 30s entre braços',
			why: [
				'Ombros retraídos, braço ao lado do corpo, levante com as pernas. <b>Nunca</b> faça pinch hangs de frente — risco de De Quervain (López).',
				'Varie a largura do bloco ao longo das 8 semanas; vá mais estreito / só polpa na Fase 2.',
			],
			swaps: [
				'Levantamentos de pinch block com peso',
				'Levantada de pinça com as duas mãos na barra',
				'Pinch hangs largos numa board de 40°+',
				'Máximo no trilho de pinça Rockstar / Tension',
			],
		},
		wrist: {
			name: 'Força de Punho / Sloper',
			cat: 'Punho',
			catVar: '--gold',
			what: 'Wrist-wrench / levantamentos radiais',
			spec: 'Hipertrofia: 20–40s até a falha @ 65–75% máx · 3–5 séries · 2 min descanso',
			why: [
				'Desenvolve o FRC + estabilizadores do punho para slopers e demanda de compressão.',
				'Ferrer-Uris 2023: sloper de 60mm ≈ ativação do FPD em half-crimp, com <b>melhor</b> FRC/FDS e menor risco de lesão.',
			],
			swaps: [
				'Levantamentos de desvio radial (wrist-wrench)',
				'Density hangs em sloper grande (60mm)',
				'Flexões de punho reversas + normais (pesadas)',
				'Board de compressão / sistema pinça-sloper',
			],
		},
		repeaters: {
			name: 'Repeaters 7/3',
			cat: 'Resistência / FC',
			catVar: '--gold',
			what: '20mm · half-crimp + mão aberta',
			spec: '~60% MVC · 7s on / 3s off ×6 = 1 série · 3–4 séries/pegada · 2 pegadas · 3 min descanso',
			why: [
				'Desenvolve capacidade glicolítica, resistência ao pump, <b>força crítica</b> — provavelmente sua lacuna real, dado o quão forte é seu máximo.',
				'Fase 2: reduza para 2–3 séries/pegada @ ~65–70% para se manter explosivo nos fins de semana.',
			],
			swaps: [
				'Repeaters 7/3 (hangboard)',
				'Repeaters 6:10 (recuperação maior)',
				'Protocolo de força crítica (4s/4s até a falha)',
				'Intervalos de voltas na parede / boulder 4×4',
			],
		},
		sport: {
			name: 'Escalada Esportiva / Voltas na Board',
			cat: 'Resistência / FC',
			catVar: '--gold',
			what: 'Submáximo, pump controlado',
			spec: 'Vias ou voltas na board · gere pump mas nunca até a falha',
			why: ['Transfere o estímulo dos repeaters para o movimento real e a capacidade aeróbica.'],
			swaps: [
				'Vias esportivas / voltas no auto-belay',
				'Volume de escalada na board (ângulo fácil)',
				'Circuito / travessia ARC 2×15–20 min',
				'Problemas de boulder encadeados (4×4)',
			],
		},
		pull: {
			name: 'Dia de Tração Pesada',
			cat: 'Potência de tração',
			catVar: '--violet',
			what: 'Pull-ups com peso + trabalho de OAP',
			spec: 'Com peso: 4–6 séries ×3–5 reps, difícil mas limpo (~+30–45kg) · OAP: negativas / assistidas, 3–4 séries/lado',
			why: [
				'Num dia de baixo custo para os dedos de propósito — potência de tração sem gastar pele ou polias.',
				'Fase 2: migre para menos reps / mais carga ou mais trabalho técnico de OAP.',
			],
			swaps: [
				'Pull-ups com peso + negativas de OAP',
				'Escada técnica de pull-up de 1 braço',
				'Frenchies / trações com peso em tempo controlado',
				'Combo front-lever + tração com peso',
			],
		},
		slopdens: {
			name: 'Density Hangs em Sloper',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'Borda inferior de um sloper',
			spec: '30–45s · 3 séries · 2 braços · posição de mão aberta',
			why: [
				'Trabalho de tecido em mão aberta que não sobrecarrega as polias — combina bem após o dia de tração.',
			],
			swaps: [
				'Density hangs em sloper',
				'Density hangs de mão aberta em 35mm',
				'Repeaters em régua grande (mão aberta)',
				'Sustentações longas de mão aberta no no-hang',
			],
		},
		maxhang: {
			name: 'Max Hangs — Manutenção',
			cat: 'Força máxima',
			catVar: '--violet',
			what: 'Dose curta · borda de ~10mm',
			spec: '3 séries ×10s · deixe 2–3s de margem · 3 min descanso (López MAW/MED, mínimo)',
			why: [
				'Você está <b>mantendo</b>, não buscando recordes — seu máximo está perto do teto e volume extra aqui é, em geral, custo de lesão.',
			],
			swaps: [
				'Max hangs 10s (10mm, com margem)',
				'MED — peso corporal em borda menor',
				'MAW — 18–20mm + peso adicional',
				'Levantamentos máximos no no-hang block (10s)',
			],
		},
		density: {
			name: 'Density Hangs',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'Sustentações longas perto da falha',
			spec: '20–40s perto da falha @ ~70–75% MVC · 5–6 séries · 3 min descanso',
			why: [
				'Seu principal investimento em tecido conjuntivo. Aumenta a rigidez do músculo + JMT enquanto <b>reduz</b> a rigidez tendínea patológica — um sistema, no saldo, mais resistente a lesões (Nelson).',
			],
			swaps: [
				'Density hangs (half-crimp)',
				'Density hangs (mão aberta)',
				'Levantamentos de densidade no no-hang block',
				'Repeaters de longa duração @ % baixo',
			],
		},
		abra: {
			name: 'Abrahangs (carga baixa)',
			cat: 'Tecido',
			catVar: '--teal',
			what: 'De manhã · 18–22mm · pés no chão',
			spec: '~40% máx ("só tensão leve") · ~10 min no total · ~20×10s entre pegadas · ≥6h do trabalho pesado',
			why: [
				'Aditivo ao trabalho máximo para a saúde do tecido (Gilmore/Baar 2024). Na sua força, mantenha estes genuinamente <b>leves</b> — erre para baixo de 40%.',
				'Isto é treino, não descanso — corte <b>estes</b> primeiro a qualquer incômodo.',
			],
			swaps: [
				'Abrahangs (no-hang, pés no chão)',
				'Sustentações leves no no-hang block',
				'Repeaters longos de % baixo',
				'Pule — descanso extra se fatigado',
			],
		},
		antag: {
			name: 'Antagonistas',
			cat: 'Prevenção',
			catVar: '--teal',
			what: '~10 min · seguro para cotovelo + polias',
			spec: 'Flexões de punho reversas 3×15 · extensões de dedo com elástico 3×20–30 · pronação/supinação 3×12 · flexões/dips',
			why: ['Essencial dada sua dominância flexora — protege cotovelos e polias.'],
			swaps: [
				'Série de antagonistas com elástico + halter',
				'Balde de arroz + elásticos extensores',
				'Só extensões de dedo com Theraband',
				'Circuito de empurrar/pronação',
			],
		},
		perform: {
			name: 'Rocha / Performance',
			cat: 'Técnica',
			catVar: '--flag',
			what: 'Hangboard = só aquecimento',
			spec: 'Sua escalada real mais difícil da semana · aquecimento completo · mentalidade de send',
			why: ['Em janelas de send o hangboard vira só ferramenta de aquecimento (Hörst).'],
			swaps: [
				'Sessão de projeto na rocha',
				'Dia de performance pesado no ginásio',
				'Sessão flash estilo competição',
				'Dia longo de vários boulders na rocha',
			],
		},
		rest: {
			name: 'Descanso Total',
			cat: 'Recuperação',
			catVar: '--ink-faint',
			what: 'Sem carga nos dedos',
			spec: 'Caminhe · mobilidade · durma · coma. A adaptação acontece agora, não na parede.',
			why: ['Mesmo no seu nível, o teto é ~3 dias de alto SNC por semana. Isso é inegociável.'],
			swaps: [
				'Descanso completo',
				'Só caminhada leve + mobilidade',
				'Aeróbico fácil (sem pegada)',
				'Abrahangs leves só se estiver doido para mexer',
			],
		},
	},
	metrics: [
		{
			id: 'rfd',
			name: 'Taxa de Desenv. de Força',
			abbr: 'RFD',
			cat: '--flag',
			unit: '%/100ms',
			desc: 'Quão rápido você atinge o pico de força. Teste: recruitment pull máximo, anote a sensação de tempo-até-o-pico ou o valor do aparelho.',
		},
		{
			id: 'contact',
			name: 'Força de Contato',
			abbr: 'CONTATO',
			cat: '--flag',
			unit: 'kg / borda',
			desc: 'Força que você segura instantaneamente em agarras pequenas. Teste: recruitment pull de 3s mais pesado numa borda fixa.',
		},
		{
			id: 'cf',
			name: 'Força Crítica',
			abbr: 'FC',
			cat: '--gold',
			unit: '% MVC',
			desc: 'Piso de força sustentável — seu teto de resistência. Teste: protocolo de repeaters até a falha.',
		},
		{
			id: 'pinch',
			name: 'Pinça Máxima',
			abbr: 'PINÇA',
			cat: '--gold',
			unit: 'kg / 7s',
			desc: 'Melhor levantamento de pinch block de 7 segundos. Teste cada braço.',
		},
		{
			id: 'pull',
			name: 'Tração com Peso',
			abbr: 'TRAÇÃO',
			cat: '--violet',
			unit: 'kg adicionais',
			desc: 'Melhor pull-up/chin-up com peso numa repetição limpa.',
		},
		{
			id: 'maxhang',
			name: 'Max Hang',
			abbr: 'MAXHANG',
			cat: '--violet',
			unit: 'kg @ 10mm',
			desc: 'Referência de manutenção — peso adicional, 10s, 10mm.',
		},
		{
			id: 'density',
			name: 'Sustentação de Densidade',
			abbr: 'DENSIDADE',
			cat: '--teal',
			unit: 'seg @ carga',
			desc: 'Maior sustentação de densidade com qualidade na carga de trabalho — proxy de capacidade de tecido.',
		},
	],
	quiz: [
		{
			id: 'recovery',
			q: 'Quão recuperado você se sente?',
			a: [
				{ t: 'Renovado e ligado', v: 2 },
				{ t: 'Normal', v: 1 },
				{ t: 'Meio apagado', v: 0 },
				{ t: 'Detonado / dolorido', v: -2 },
			],
		},
		{
			id: 'fingers',
			q: 'Como estão seus dedos?',
			a: [
				{ t: '100% — sem incômodos', v: 2 },
				{ t: 'Bem, leve rigidez', v: 1 },
				{ t: 'Sensível numa articulação/polia', v: -2 },
				{ t: 'Dor aguda em qualquer lugar', v: -5 },
			],
		},
		{
			id: 'slot',
			q: 'Qual a janela hoje?',
			a: [
				{ t: 'Sessão grande, bastante tempo', v: 2 },
				{ t: 'Sessão padrão', v: 1 },
				{ t: 'Curta — 30–45 min', v: 0 },
				{ t: 'Quase sem tempo', v: -1 },
			],
		},
		{
			id: 'skin',
			q: 'Pele e SNC / disposição?',
			a: [
				{ t: 'Pele boa, me sentindo afiado', v: 2 },
				{ t: 'Ok', v: 1 },
				{ t: 'Pele fina / pouca disposição', v: -1 },
				{ t: 'Os dois zerados', v: -2 },
			],
		},
	],
	verdicts: {
		rest: {
			title: 'Pare — descanse os dedos',
			tag: 'Protocolo de dor',
			color: 'var(--flag)',
			text: 'Dor aguda no dedo é parada obrigatória. <b>Nenhuma carga hoje.</b> Lesões de polia são ~60% das lesões de dedo e vêm justamente de forçar nisso. Se persistir além de 3–5 dias, procure avaliação. Hoje: mobilidade leve, sono, comida.',
			focus: ['DESCANSO', 'avaliar', 'sem hangboard'],
		},
		tissue: {
			title: 'Dia de tecido / recuperação',
			tag: 'Só carga baixa',
			color: 'var(--teal)',
			text: 'Você está sub-recuperado ou carregando um incômodo. Faça <b>só trabalho de tecido de carga baixa</b>: Abrahangs leves (bem abaixo de 40%), antagonistas, mobilidade fácil. Isto é produtivo — o tecido conjuntivo é seu gargalo de qualquer forma — e protege os dias duros.',
			focus: ['Abrahangs', 'antagonistas', 'mobilidade de punho'],
		},
		moderate: {
			title: 'Moderado — resistência ou tipo de pegada',
			tag: 'Qualidade, não máximo',
			color: 'var(--gold)',
			text: 'Bom o bastante para treinar, não para ir ao limite. Melhores escolhas: <b>repeaters 7/3</b> para força crítica, ou uma sessão de <b>pinça / punho / sloper</b>. Evite recruitment máximo e boulder no limite hoje — poupe o SNC.',
			focus: ['repeaters', 'pinça', 'sloper', 'força crítica'],
		},
		short: {
			title: 'Curto e afiado — força de contato',
			tag: 'Alto valor, baixo volume',
			color: 'var(--flag)',
			text: 'Você está descansado mas com pouco tempo. Perfeito para <b>recruitment pulls</b> — 2–3 séries treinam RFD e força de contato em ~15 min com fadiga mínima. Aqueça bem antes; qualidade acima de quantidade.',
			focus: ['recruitment pulls', 'RFD', 'força de contato'],
		},
		green: {
			title: 'Sinal verde — vá com tudo',
			tag: 'Dia de limite / máximo',
			color: 'var(--flag)',
			text: 'Descansado, dedos bons, tempo e pele para gastar. Faça um <b>dia duro</b>: recruitment pulls emendando em <b>boulder no limite</b>, ou um dia de tração pesada. Descanse totalmente entre os esforços máximos. Abasteça colágeno ~60 min antes: 15g de colágeno + 50mg de vit C.',
			focus: ['recruitment pulls', 'boulder no limite', 'tração pesada'],
		},
	},
	phases: {
		phase1: {
			name: 'Fase 1 · Capacidade & Base de Tecido (Sem 1–4)',
			banner:
				'Construa qualidade de recruitment, estabeleça o máximo de pinça de 7s, maior volume de repeaters, construa volume de tração + negativas de OAP, densidade completa. Colágeno + vit C ~60 min antes da sessão de dedo mais pesada.',
			cat: '--gold',
		},
		phase2: {
			name: 'Fase 2 · Expressão & Pico (Sem 5–7)',
			banner:
				'Enfatize força de contato em agarras piores; pinça mais estreita; corte séries de repeaters para manter a potência; tração migra para menos reps/mais carga. Max hangs seguem mínimos.',
			cat: '--flag',
		},
		deload: {
			name: 'Semana 8 · Deload',
			banner:
				'Reduza volume E intensidade pela metade. Duas sessões curtas de hangboard, margens grandes. Só escalada fácil. MANTENHA Abrahangs leves — descarregar de verdade custa ~10–20% do colágeno tendíneo em dias (Baar). As adaptações aparecem agora, conforme a fadiga some. Reteste no fim da semana.',
			cat: '--teal',
		},
	},
	glossary: {
		SNC: 'Sistema nervoso central — a fadiga sistêmica que limita esforços máximos e intensos.',
		RFD: 'Taxa de desenvolvimento de força — quão rápido você atinge o pico de força.',
		MVC: 'Contração voluntária máxima — sua força máxima numa dada pegada.',
		JMT: 'Junção miotendínea — onde o músculo vira tendão.',
		OAP: 'Pull-up de um braço (one-arm pull-up).',
		FRC: 'Flexor radial do carpo — um flexor do punho do lado do polegar.',
		FPD: 'Flexor profundo dos dedos — o flexor profundo que comanda o crimp.',
		FDS: 'Flexor superficial dos dedos.',
		FC: 'Força crítica — a maior força que você sustenta quase indefinidamente; seu piso de resistência.',
		MAW: 'Max Added Weight — protocolo de hangboard da López: borda fixa, adicionar peso.',
		MED: 'Minimum Edge Depth — protocolo da López: peso corporal em borda cada vez menor.',
		ARC: 'Aerobic Restoration & Capillarity — escalada contínua fácil para base de resistência.',
		'De Quervain':
			'Tenossinovite de De Quervain — irritação dos tendões do punho do lado do polegar.',
	},
};

export default content;
